--------------------------------------------------------
--  DDL for Table ADMIN_CHG_LOG
--------------------------------------------------------

  CREATE TABLE "ADMIN_CHG_LOG" 
   (	"CHG_LOG_ID" NUMBER(12,0), 
	"TABLE_ID" NUMBER(12,0), 
	"TABLE_NAME" VARCHAR2(30 BYTE), 
	"COLUMN_NAME" VARCHAR2(30 BYTE), 
	"CHANGE" VARCHAR2(255 BYTE), 
	"MDU" VARCHAR2(30 BYTE), 
	"TIME_STAMP" TIMESTAMP (6) DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "ADMIN_CHG_LOG"."CHG_LOG_ID" IS 'Változtatás típusa egyedi azonosítója';
 
   COMMENT ON COLUMN "ADMIN_CHG_LOG"."TABLE_ID" IS 'Tábla sorának egyedi azonosítója';
 
   COMMENT ON COLUMN "ADMIN_CHG_LOG"."TABLE_NAME" IS 'Tábla neve';
 
   COMMENT ON COLUMN "ADMIN_CHG_LOG"."COLUMN_NAME" IS 'Oszlop név';
 
   COMMENT ON COLUMN "ADMIN_CHG_LOG"."CHANGE" IS 'Változtatás típusa';
 
   COMMENT ON COLUMN "ADMIN_CHG_LOG"."MDU" IS 'Rekord Módosítójának Azonosítója';
 
   COMMENT ON COLUMN "ADMIN_CHG_LOG"."TIME_STAMP" IS 'Időpecsét';
 
   COMMENT ON TABLE "ADMIN_CHG_LOG"  IS 'Adminisztrációs változáskezelési tábla
Code: CLOG';
