--------------------------------------------------------
--  DDL for Table ADMIN_VER_INFO
--------------------------------------------------------

  CREATE TABLE "ADMIN_VER_INFO" 
   (	"VER_INFO_ID" NUMBER(12,0), 
	"SCH_NAME" VARCHAR2(30 BYTE), 
	"VER_INFO" VARCHAR2(30 BYTE), 
	"TIME_STAMP" TIMESTAMP (6) DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "ADMIN_VER_INFO"."VER_INFO_ID" IS 'Adatbázis és program verziótáblájának egyedi azonosítója';
 
   COMMENT ON COLUMN "ADMIN_VER_INFO"."SCH_NAME" IS 'Feldolgozott Schéma neve';
 
   COMMENT ON COLUMN "ADMIN_VER_INFO"."VER_INFO" IS 'Adatbázis és program verziójának aktuális értéke';
 
   COMMENT ON COLUMN "ADMIN_VER_INFO"."TIME_STAMP" IS 'Időpecsét';
 
   COMMENT ON TABLE "ADMIN_VER_INFO"  IS 'Adminisztratív verzió kezelő tábla
Code:AINF';
