--------------------------------------------------------
--  Constraints for Table ADMIN_VER_INFO
--------------------------------------------------------

  ALTER TABLE "ADMIN_VER_INFO" ADD CONSTRAINT "PK_ADMIN_VER_INFO" PRIMARY KEY ("VER_INFO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN_VER_INFO" MODIFY ("VER_INFO_ID" NOT NULL ENABLE);
