--------------------------------------------------------
--  Constraints for Table ADMIN_AVC_LOG
--------------------------------------------------------

  ALTER TABLE "ADMIN_AVC_LOG" ADD CONSTRAINT "PK_ADMIN_AVC_LOG" PRIMARY KEY ("AVC_LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "ADMIN_AVC_LOG" MODIFY ("AVC_LOG_ID" NOT NULL ENABLE);
