--------------------------------------------------------
--  Constraints for Table DATA_INCO
--------------------------------------------------------

  ALTER TABLE "DATA_INCO" ADD CONSTRAINT "PK_ADAT_BEE" PRIMARY KEY ("DATA_INCO_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DATA_INCO" MODIFY ("DATA_INCO_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DATA_INCO" MODIFY ("SUBJ_ID" NOT NULL ENABLE);
