--------------------------------------------------------
--  Constraints for Table DM_ANALYSIS_MET
--------------------------------------------------------

  ALTER TABLE "DM_ANALYSIS_MET" ADD CONSTRAINT "PK_DM_ANALYSIS_MET" PRIMARY KEY ("ANALYSIS_MET_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DM_ANALYSIS_MET" MODIFY ("ANALYSIS_MET_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_ANALYSIS_MET" MODIFY ("STATUS_ID" NOT NULL ENABLE);
