--------------------------------------------------------
--  DDL for Table DM_CURRENCY_CHANGE
--------------------------------------------------------

  CREATE TABLE "DM_CURRENCY_CHANGE" 
   (	"CURR_CHANG_ID" NUMBER(12,0), 
	"CURR_CODE_FROM" VARCHAR2(3 CHAR), 
	"CURR_VALUE_FROM" NUMBER(6,2) DEFAULT 1, 
	"CURR_CODE_TO" VARCHAR2(3 CHAR) DEFAULT 'HUF', 
	"CURR_VALUE_TO" NUMBER(6,2), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"STATUS_ID" NUMBER(12,0) DEFAULT 912, 
	"CRU" VARCHAR2(30 BYTE), 
	"CRD" TIMESTAMP (6) DEFAULT SYSDATE, 
	"MDU" VARCHAR2(30 BYTE), 
	"MDD" TIMESTAMP (6), 
	"PROVIDER" NUMBER(12,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "DM_CURRENCY_CHANGE"."CURR_CHANG_ID" IS 'A tábla egyedi azonosítója';
 
   COMMENT ON COLUMN "DM_CURRENCY_CHANGE"."FROM_DATE" IS 'Érvényesség kezdő időpontja';
 
   COMMENT ON COLUMN "DM_CURRENCY_CHANGE"."TO_DATE" IS 'Érvényesség vége';
 
   COMMENT ON COLUMN "DM_CURRENCY_CHANGE"."DESCRIPTION" IS 'Leírás';
 
   COMMENT ON COLUMN "DM_CURRENCY_CHANGE"."STATUS_ID" IS 'Az adat státuszának, feldolgozottságának egyedi azonosítója';
 
   COMMENT ON COLUMN "DM_CURRENCY_CHANGE"."CRU" IS 'Rekord Létrehozójának Azonosítója';
 
   COMMENT ON COLUMN "DM_CURRENCY_CHANGE"."CRD" IS 'Rekord Létrehozásának időpecsétje';
 
   COMMENT ON COLUMN "DM_CURRENCY_CHANGE"."MDU" IS 'Rekord Módosítójának Azonosítója';
 
   COMMENT ON TABLE "DM_CURRENCY_CHANGE"  IS 'Valuta váltási értékek';
