--------------------------------------------------------
--  Constraints for Table DM_COUNTRY
--------------------------------------------------------

  ALTER TABLE "DM_COUNTRY" ADD CONSTRAINT "PK_DM_COUNTRY" PRIMARY KEY ("COUNTRY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "DM_COUNTRY" MODIFY ("STATUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_COUNTRY" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
