REM INSERTING into DM_MESSAGE
SET DEFINE OFF;
Insert into DM_MESSAGE (MESSAGE_ID,LANGUAGE_ID,MESSAGE_TEXT,MESSAGE_TYPE_ID,PARAM_VALUE1,PARAM_TYPE1,DESCRIPTION,FROM_DATE,TO_DATE,CRU,CRD,MDU,MDD,STATUS_ID) values ('200','1','Havi jelentés ellenőrzése','100',null,null,null,null,null,null,null,null,null,'3');
Insert into DM_MESSAGE (MESSAGE_ID,LANGUAGE_ID,MESSAGE_TEXT,MESSAGE_TYPE_ID,PARAM_VALUE1,PARAM_TYPE1,DESCRIPTION,FROM_DATE,TO_DATE,CRU,CRD,MDU,MDD,STATUS_ID) values ('201','1','Havi jelentés készítése','100',null,null,null,null,null,null,null,null,null,'3');
Insert into DM_MESSAGE (MESSAGE_ID,LANGUAGE_ID,MESSAGE_TEXT,MESSAGE_TYPE_ID,PARAM_VALUE1,PARAM_TYPE1,DESCRIPTION,FROM_DATE,TO_DATE,CRU,CRD,MDU,MDD,STATUS_ID) values ('101','1','Egy késő üzenet','100',null,null,null,null,null,null,null,null,null,'3');
Insert into DM_MESSAGE (MESSAGE_ID,LANGUAGE_ID,MESSAGE_TEXT,MESSAGE_TYPE_ID,PARAM_VALUE1,PARAM_TYPE1,DESCRIPTION,FROM_DATE,TO_DATE,CRU,CRD,MDU,MDD,STATUS_ID) values ('100','1','Üzenet a liftből','100',null,null,null,null,null,null,null,null,null,'3');
