REM INSERTING into DM_ROLE_RIGHT
SET DEFINE OFF;
Insert into DM_ROLE_RIGHT (ROLE_RIGHT_ID,ROLE_ID,APEX_PAGE,APEX_VARIABLE,TCRITERION,FROM_DATE,TO_DATE,DESCRIPTION,CRU,CRD,MDU,MDD) values ('100','0','4100',null,null,null,null,null,null,to_timestamp('13-NOV.  -16 08.26.11,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null);
Insert into DM_ROLE_RIGHT (ROLE_RIGHT_ID,ROLE_ID,APEX_PAGE,APEX_VARIABLE,TCRITERION,FROM_DATE,TO_DATE,DESCRIPTION,CRU,CRD,MDU,MDD) values ('101','0','4110',null,null,null,null,null,null,to_timestamp('13-NOV.  -16 08.26.11,000000000','RR-MON-DD HH24.MI.SSXFF'),null,null);
