--------------------------------------------------------
--  Constraints for Table DM_USER
--------------------------------------------------------

  ALTER TABLE "DM_USER" MODIFY ("STATUS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "DM_USER" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "DM_USER" ADD CONSTRAINT "UK_DMUS" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
