--------------------------------------------------------
--  DDL for Index FK_EPRE_EP1ID
--------------------------------------------------------

  CREATE INDEX "FK_EPRE_EP1ID" ON "EPI_REL" ("EPI_ID1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
