--------------------------------------------------------
--  File created - vasárnap-március-22-2015   
--------------------------------------------------------
@C:\work\EltesoftLocal\obh_test\DM_XL_ROW_TYPE.sql
@C:\work\EltesoftLocal\obh_test\DM_XL_TAB_TYPE.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168552_DUMMY_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168552_112_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168552_140_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168573_DUMMY_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168573_104_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168573_150_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168573_158_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168573_340_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168573_348_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168573_410_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168573_47_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168573_9_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168573_96_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168591_DUMMY_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168591_33_1.sql
@C:\work\EltesoftLocal\obh_test\SYS_PLSQL_168591_78_1.sql
@C:\work\EltesoftLocal\obh_test\T_CSV_LINE.sql
@C:\work\EltesoftLocal\obh_test\T_CSV_TAB.sql
@C:\work\EltesoftLocal\obh_test\T_DATE_ARRAY.sql
@C:\work\EltesoftLocal\obh_test\T_DICTIONARY.sql
@C:\work\EltesoftLocal\obh_test\T_NAME_VALUE_PAIR.sql
@C:\work\EltesoftLocal\obh_test\T_NUM_ARRAY.sql
@C:\work\EltesoftLocal\obh_test\T_SOAP_ENVELOPE.sql
@C:\work\EltesoftLocal\obh_test\T_STR_ARRAY.sql
@C:\work\EltesoftLocal\obh_test\CATUS_SEQID.sql
@C:\work\EltesoftLocal\obh_test\SEQ_ADMIN.sql
@C:\work\EltesoftLocal\obh_test\SEQ_BASE.sql
@C:\work\EltesoftLocal\obh_test\SEQ_INSWK.sql
@C:\work\EltesoftLocal\obh_test\SEQ_LTRG_ID.sql
@C:\work\EltesoftLocal\obh_test\SEQ_NEW.sql
@C:\work\EltesoftLocal\obh_test\SEQ_TESTRPT.sql
@C:\work\EltesoftLocal\obh_test\SEQ_WKDENT.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_AVC_LOG.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_CHG_LOG.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_DBA_LOG.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_EVAL_LOG.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_VER_INFO.sql
@C:\work\EltesoftLocal\obh_test\ALERT.sql
@C:\work\EltesoftLocal\obh_test\ALERT_PARAM.sql
@C:\work\EltesoftLocal\obh_test\APEX_MENU_TEMP.sql
@C:\work\EltesoftLocal\obh_test\CELL_COMMENTS.sql
@C:\work\EltesoftLocal\obh_test\DATA_INCO.sql
@C:\work\EltesoftLocal\obh_test\DEV_TEMP.sql
@C:\work\EltesoftLocal\obh_test\DM_ANALYSIS_MET.sql
@C:\work\EltesoftLocal\obh_test\DM_ANALYSIS_TYP.sql
@C:\work\EltesoftLocal\obh_test\DM_CATEGORY.sql
@C:\work\EltesoftLocal\obh_test\DM_CAT_USAGE.sql
@C:\work\EltesoftLocal\obh_test\DM_COUNTRY.sql
@C:\work\EltesoftLocal\obh_test\DM_CURRENCY_CHANGE.sql
@C:\work\EltesoftLocal\obh_test\DM_EXCELL_COLUMNS.sql
@C:\work\EltesoftLocal\obh_test\DM_LANGUAGE.sql
@C:\work\EltesoftLocal\obh_test\DM_MESSAGE.sql
@C:\work\EltesoftLocal\obh_test\DM_NAMES.sql
@C:\work\EltesoftLocal\obh_test\DM_REGULATION.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE_RIGHT.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE_USER.sql
@C:\work\EltesoftLocal\obh_test\DM_SALUTATION.sql
@C:\work\EltesoftLocal\obh_test\DM_SUPER_TYP.sql
@C:\work\EltesoftLocal\obh_test\DM_SUPER_TYP_REL.sql
@C:\work\EltesoftLocal\obh_test\DM_TEXT.sql
@C:\work\EltesoftLocal\obh_test\DM_TRANSLATE.sql
@C:\work\EltesoftLocal\obh_test\DM_USER.sql
@C:\work\EltesoftLocal\obh_test\DM_XL.sql
@C:\work\EltesoftLocal\obh_test\DM_XL_REL.sql
@C:\work\EltesoftLocal\obh_test\EPI.sql
@C:\work\EltesoftLocal\obh_test\EPI_PARAM.sql
@C:\work\EltesoftLocal\obh_test\EPI_REL.sql
@C:\work\EltesoftLocal\obh_test\EPI_TREATM.sql
@C:\work\EltesoftLocal\obh_test\EPI_TREATM_PARAM.sql
@C:\work\EltesoftLocal\obh_test\GIS_DATA.sql
@C:\work\EltesoftLocal\obh_test\GIS_DATA_REL.sql
@C:\work\EltesoftLocal\obh_test\GIS_REL_PARAM.sql
@C:\work\EltesoftLocal\obh_test\GIS_SUBJ_EPI_REL.sql
@C:\work\EltesoftLocal\obh_test\INVENT.sql
@C:\work\EltesoftLocal\obh_test\INVENT_PARAM.sql
@C:\work\EltesoftLocal\obh_test\LOG_TABLE.sql
@C:\work\EltesoftLocal\obh_test\MM_FILES.sql
@C:\work\EltesoftLocal\obh_test\PRT_IC_HEAD.sql
@C:\work\EltesoftLocal\obh_test\PRT_IC_ITEM.sql
@C:\work\EltesoftLocal\obh_test\PRT_TREATM.sql
@C:\work\EltesoftLocal\obh_test\PRT_TREATM_REL.sql
@C:\work\EltesoftLocal\obh_test\PRT_WORK_TIME.sql
@C:\work\EltesoftLocal\obh_test\SUBJECT.sql
@C:\work\EltesoftLocal\obh_test\SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\SUBJ_REL.sql
@C:\work\EltesoftLocal\obh_test\TIME_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TRAFFIC_SUM.sql
@C:\work\EltesoftLocal\obh_test\TREATM.sql
@C:\work\EltesoftLocal\obh_test\TREATM_COPY_TEMP.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PARAM.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PRU.sql
@C:\work\EltesoftLocal\obh_test\TREATM_REL.sql
@C:\work\EltesoftLocal\obh_test\TR_XL.sql
@C:\work\EltesoftLocal\obh_test\TR_XL_LOAD_ERR.sql
@C:\work\EltesoftLocal\obh_test\USERS_DEFAULTS.sql
@C:\work\EltesoftLocal\obh_test\VALID_UNIT.sql
@C:\work\EltesoftLocal\obh_test\VERSION_INFO.sql
@C:\work\EltesoftLocal\obh_test\WK_DM_SUPER_TYP.sql
@C:\work\EltesoftLocal\obh_test\WK_PF_AUDIT_TABLE.sql
@C:\work\EltesoftLocal\obh_test\WK_PF_MENU.sql
@C:\work\EltesoftLocal\obh_test\APEXLIB_V_PAGE.sql
@C:\work\EltesoftLocal\obh_test\APEXLIB_V_PAGE_BRANCH.sql
@C:\work\EltesoftLocal\obh_test\APEXLIB_V_PAGE_ITEM.sql
@C:\work\EltesoftLocal\obh_test\APEXLIB_V_PAGE_REGION.sql
@C:\work\EltesoftLocal\obh_test\APEXLIB_V_PAGE_VALIDATION.sql
@C:\work\EltesoftLocal\obh_test\APEXLIB_V_REPORT_COLUMN.sql
@C:\work\EltesoftLocal\obh_test\V_ADAT_BEERKEZES.sql
@C:\work\EltesoftLocal\obh_test\V_DM_EXCELL_COLUMNS.sql
@C:\work\EltesoftLocal\obh_test\V_DM_ROLE.sql
@C:\work\EltesoftLocal\obh_test\V_DM_XL_REL.sql
@C:\work\EltesoftLocal\obh_test\V_DM_XL_REL_SOR_SOR.sql
@C:\work\EltesoftLocal\obh_test\V_EPI.sql
@C:\work\EltesoftLocal\obh_test\V_EPI_SUBJ.sql
@C:\work\EltesoftLocal\obh_test\V_EPI_SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\V_EPI_SUBJ1_SUBJ2_GIS.sql
@C:\work\EltesoftLocal\obh_test\V_GIS_SUBJ_EPI_REL.sql
@C:\work\EltesoftLocal\obh_test\V_INTERVALL.sql
@C:\work\EltesoftLocal\obh_test\V_INVENT.sql
@C:\work\EltesoftLocal\obh_test\V_INVENT_EPI_PARAM.sql
@C:\work\EltesoftLocal\obh_test\V_INVENT_EPISODES.sql
@C:\work\EltesoftLocal\obh_test\V_INVENT_INVENT_PARAM.sql
@C:\work\EltesoftLocal\obh_test\V_INVENT_PARAM.sql
@C:\work\EltesoftLocal\obh_test\V_LIST_EPI_SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\V_LIST_SUBJ.sql
@C:\work\EltesoftLocal\obh_test\V_LOG_TABLE.sql
@C:\work\EltesoftLocal\obh_test\V_MENU.sql
@C:\work\EltesoftLocal\obh_test\V_MENU_1007.sql
@C:\work\EltesoftLocal\obh_test\V_MENU_1012.sql
@C:\work\EltesoftLocal\obh_test\V_MM_FILES.sql
@C:\work\EltesoftLocal\obh_test\V_PF_DM_XL.sql
@C:\work\EltesoftLocal\obh_test\V_SUBJECTIV.sql
@C:\work\EltesoftLocal\obh_test\V_SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\V_SUBJ_REL.sql
@C:\work\EltesoftLocal\obh_test\VT_DM_LANGUAGE.sql
@C:\work\EltesoftLocal\obh_test\VT_DM_SUPER_TYP.sql
@C:\work\EltesoftLocal\obh_test\VT_DM_SUPER_TYP1.sql
@C:\work\EltesoftLocal\obh_test\VT_DM_TRANSLATE.sql
@C:\work\EltesoftLocal\obh_test\VT_GIS_DATA.sql
@C:\work\EltesoftLocal\obh_test\V_TIME_TABLE.sql
@C:\work\EltesoftLocal\obh_test\VT_PIVOT_TEXT.sql
@C:\work\EltesoftLocal\obh_test\V_TREATM_CHILDS.sql
@C:\work\EltesoftLocal\obh_test\V_TREATM_DOCS.sql
@C:\work\EltesoftLocal\obh_test\V_TREATMENT_S.sql
@C:\work\EltesoftLocal\obh_test\V_TREATM_K.sql
@C:\work\EltesoftLocal\obh_test\V_TREATM_LIST.sql
@C:\work\EltesoftLocal\obh_test\V_TREATM_N.sql
@C:\work\EltesoftLocal\obh_test\V_TREATM_PRU_SCR.sql
@C:\work\EltesoftLocal\obh_test\V_TREATM_T.sql
@C:\work\EltesoftLocal\obh_test\V_USER_EFF_RIGHTS.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_AVC_LOG_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_CHG_LOG_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_DBA_LOG_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_EVAL_LOG_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_VER_INFO_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\ALERT_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\ALERT_PARAM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\APEX_MENU_TEMP_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\CELL_COMMENTS_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DATA_INCO_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DEV_TEMP_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_ANALYSIS_MET_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_ANALYSIS_TYP_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_CATEGORY_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_CAT_USAGE_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_COUNTRY_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_CURRENCY_CHANGE_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_EXCELL_COLUMNS_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_LANGUAGE_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_MESSAGE_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_NAMES_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_REGULATION_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE_RIGHT_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE_USER_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_SALUTATION_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_SUPER_TYP_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_SUPER_TYP_REL_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_TEXT_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_TRANSLATE_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_USER_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_XL_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\DM_XL_REL_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\EPI_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\EPI_PARAM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\EPI_REL_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\EPI_TREATM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\EPI_TREATM_PARAM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\GIS_DATA_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\GIS_DATA_REL_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\GIS_REL_PARAM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\GIS_SUBJ_EPI_REL_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\INVENT_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\INVENT_PARAM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\LOG_TABLE_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\MM_FILES_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\PRT_IC_HEAD_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\PRT_IC_ITEM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\PRT_TREATM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\PRT_TREATM_REL_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\PRT_WORK_TIME_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\SUBJECT_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\SUBJ_PARAM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\SUBJ_REL_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TIME_TABLE_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TRAFFIC_SUM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TREATM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TREATM_COPY_TEMP_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PARAM_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PRU_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TREATM_REL_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TR_XL_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TR_XL_LOAD_ERR_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\USERS_DEFAULTS_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\VALID_UNIT_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\VERSION_INFO_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\WK_DM_SUPER_TYP_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\WK_PF_AUDIT_TABLE_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\WK_PF_MENU_DATA_TABLE.sql
@C:\work\EltesoftLocal\obh_test\PK_TRAFFIC_SUM.sql
@C:\work\EltesoftLocal\obh_test\NDX__DMRU.sql
@C:\work\EltesoftLocal\obh_test\PK_DM_CAT_USAGE.sql
@C:\work\EltesoftLocal\obh_test\NDX_WKTI.sql
@C:\work\EltesoftLocal\obh_test\NDX_DMRG.sql
@C:\work\EltesoftLocal\obh_test\NDX_SUPA_PT.sql
@C:\work\EltesoftLocal\obh_test\UK_DMRR.sql
@C:\work\EltesoftLocal\obh_test\NDX_EINP_1.sql
@C:\work\EltesoftLocal\obh_test\VDX_TRTM.sql
@C:\work\EltesoftLocal\obh_test\APEX_MENU_TEMP_PK.sql
@C:\work\EltesoftLocal\obh_test\PK_EPI_INVENT_PARAM.sql
@C:\work\EltesoftLocal\obh_test\NDX_SUPA_VA.sql
@C:\work\EltesoftLocal\obh_test\UK_DMSL.sql
@C:\work\EltesoftLocal\obh_test\NDX_LGTBL5.sql
@C:\work\EltesoftLocal\obh_test\PK_SUBJ_REL.sql
@C:\work\EltesoftLocal\obh_test\FK_TIMT_SUBID.sql
@C:\work\EltesoftLocal\obh_test\PK_SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\PK_ADAT_BEE.sql
@C:\work\EltesoftLocal\obh_test\PK_TIME_TABLE.sql
@C:\work\EltesoftLocal\obh_test\PK_DM_ROLE_RIGHT.sql
@C:\work\EltesoftLocal\obh_test\PK_DMRR.sql
@C:\work\EltesoftLocal\obh_test\VDX_EINP.sql
@C:\work\EltesoftLocal\obh_test\AK_UK_PICI_PRT_IC_I.sql
@C:\work\EltesoftLocal\obh_test\FK_EPRE_EP1ID.sql
@C:\work\EltesoftLocal\obh_test\NDX_EPIS.sql
@C:\work\EltesoftLocal\obh_test\NDX_SUPA_VT.sql
@C:\work\EltesoftLocal\obh_test\PK_CCOM_CC.sql
@C:\work\EltesoftLocal\obh_test\UK_DMUS_1.sql
@C:\work\EltesoftLocal\obh_test\PK__PICI.sql
@C:\work\EltesoftLocal\obh_test\NDX_CLOG_1.sql
@C:\work\EltesoftLocal\obh_test\PK_ADMIN_VER_INFO.sql
@C:\work\EltesoftLocal\obh_test\NDX_ALRT_2.sql
@C:\work\EltesoftLocal\obh_test\VDX_SURE.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PRU_PK.sql
@C:\work\EltesoftLocal\obh_test\NDX_LGTBL4.sql
@C:\work\EltesoftLocal\obh_test\NDX_EPIV_2.sql
@C:\work\EltesoftLocal\obh_test\UK_DMTX.sql
@C:\work\EltesoftLocal\obh_test\NDX_DMCO_1.sql
@C:\work\EltesoftLocal\obh_test\NDX_ALRT_1.sql
@C:\work\EltesoftLocal\obh_test\PK_DM_COUNTRY.sql
@C:\work\EltesoftLocal\obh_test\NDX_LGTBL1.sql
@C:\work\EltesoftLocal\obh_test\DM_REGULATION_INDEX1.sql
@C:\work\EltesoftLocal\obh_test\PK_GIS_REL_PARAM.sql
@C:\work\EltesoftLocal\obh_test\NDX_EPIV_3.sql
@C:\work\EltesoftLocal\obh_test\NDX_DMSL.sql
@C:\work\EltesoftLocal\obh_test\KEY_SUBJECT_SUBJ_ID.sql
@C:\work\EltesoftLocal\obh_test\UK_DMUS_2.sql
@C:\work\EltesoftLocal\obh_test\PK_ADMIN_AVC_LOG.sql
@C:\work\EltesoftLocal\obh_test\PK_TR_TR.sql
@C:\work\EltesoftLocal\obh_test\PK_GIS_DATA.sql
@C:\work\EltesoftLocal\obh_test\PK_DM_LANGUAGE.sql
@C:\work\EltesoftLocal\obh_test\NDX_ETRP.sql
@C:\work\EltesoftLocal\obh_test\NDX_TRTR_2.sql
@C:\work\EltesoftLocal\obh_test\PK_TR_XL.sql
@C:\work\EltesoftLocal\obh_test\PK_WK_TIME.sql
@C:\work\EltesoftLocal\obh_test\PK_ADMIN_CHG_LOG.sql
@C:\work\EltesoftLocal\obh_test\UQ_DMCU.sql
@C:\work\EltesoftLocal\obh_test\NDX_PICH.sql
@C:\work\EltesoftLocal\obh_test\PK_DM_MESSAGE.sql
@C:\work\EltesoftLocal\obh_test\NDX_AINF.sql
@C:\work\EltesoftLocal\obh_test\NDX_TIMT_1.sql
@C:\work\EltesoftLocal\obh_test\PK_ALERT_PARAM.sql
@C:\work\EltesoftLocal\obh_test\PK_GIS_SUBJ_EPI_REL.sql
@C:\work\EltesoftLocal\obh_test\NDX_SUPA.sql
@C:\work\EltesoftLocal\obh_test\UK_DMNA.sql
@C:\work\EltesoftLocal\obh_test\NDX_TIMT_2.sql
@C:\work\EltesoftLocal\obh_test\NDX_VINF.sql
@C:\work\EltesoftLocal\obh_test\VDX_EPTR.sql
@C:\work\EltesoftLocal\obh_test\NDX_PICH_1.sql
@C:\work\EltesoftLocal\obh_test\NDX_GRPM.sql
@C:\work\EltesoftLocal\obh_test\NDX_SURE_3.sql
@C:\work\EltesoftLocal\obh_test\NDX_CLOG_2.sql
@C:\work\EltesoftLocal\obh_test\PK_GIS_DATA_REL.sql
@C:\work\EltesoftLocal\obh_test\NDX_DMCO_2.sql
@C:\work\EltesoftLocal\obh_test\VDX_ETRP.sql
@C:\work\EltesoftLocal\obh_test\NDX_DMTR_1.sql
@C:\work\EltesoftLocal\obh_test\PK_MM_FILES.sql
@C:\work\EltesoftLocal\obh_test\NDX_GSER_.sql
@C:\work\EltesoftLocal\obh_test\NDX_DLOG.sql
@C:\work\EltesoftLocal\obh_test\AK_UK_EPRE_EPI_REL.sql
@C:\work\EltesoftLocal\obh_test\PK_DM_SALUTATION.sql
@C:\work\EltesoftLocal\obh_test\IDX_TR_XL.sql
@C:\work\EltesoftLocal\obh_test\NDX_SURE.sql
@C:\work\EltesoftLocal\obh_test\NDX_DMTR_2.sql
@C:\work\EltesoftLocal\obh_test\PK_VALU.sql
@C:\work\EltesoftLocal\obh_test\NDX_ETRP_2.sql
@C:\work\EltesoftLocal\obh_test\NDX_DMTR.sql
@C:\work\EltesoftLocal\obh_test\NDX_DMAN.sql
@C:\work\EltesoftLocal\obh_test\PK_ALERT.sql
@C:\work\EltesoftLocal\obh_test\AK_PK_EPRE_EPI_REL.sql
@C:\work\EltesoftLocal\obh_test\NDX_PICI.sql
@C:\work\EltesoftLocal\obh_test\VDX_TRTR.sql
@C:\work\EltesoftLocal\obh_test\DM_SUPER_TYP_PK.sql
@C:\work\EltesoftLocal\obh_test\PK_DM_ROLE.sql
@C:\work\EltesoftLocal\obh_test\NDX_LGTBL3.sql
@C:\work\EltesoftLocal\obh_test\NDX_GIDA2.sql
@C:\work\EltesoftLocal\obh_test\VDX_TIMT.sql
@C:\work\EltesoftLocal\obh_test\NDX_TRTR_1.sql
@C:\work\EltesoftLocal\obh_test\PK_TREATM_COPY_TEMP.sql
@C:\work\EltesoftLocal\obh_test\PK_EPI_SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\PK_PRT_IC_HEAD.sql
@C:\work\EltesoftLocal\obh_test\NDX_GSER_REL.sql
@C:\work\EltesoftLocal\obh_test\PK_ADMIN_DBA_LOG.sql
@C:\work\EltesoftLocal\obh_test\NDX_GIDA.sql
@C:\work\EltesoftLocal\obh_test\NDX_GDRE.sql
@C:\work\EltesoftLocal\obh_test\NDX_LGTBL2.sql
@C:\work\EltesoftLocal\obh_test\PK_EPI_INVENT.sql
@C:\work\EltesoftLocal\obh_test\PK_EPI.sql
@C:\work\EltesoftLocal\obh_test\PK_ADMIN_EVAL_LOG.sql
@C:\work\EltesoftLocal\obh_test\NDX_ELOG.sql
@C:\work\EltesoftLocal\obh_test\NDX_ALOG.sql
@C:\work\EltesoftLocal\obh_test\UK_DMUS.sql
@C:\work\EltesoftLocal\obh_test\NDX_VALU.sql
@C:\work\EltesoftLocal\obh_test\NDX_SURE_2.sql
@C:\work\EltesoftLocal\obh_test\PK_TREATM_PARAM.sql
@C:\work\EltesoftLocal\obh_test\PK_USERS_DEFAULTS.sql
@C:\work\EltesoftLocal\obh_test\PK_DM_NAMES.sql
@C:\work\EltesoftLocal\obh_test\NDX_DMMG.sql
@C:\work\EltesoftLocal\obh_test\PK_VERSION_INFO.sql
@C:\work\EltesoftLocal\obh_test\NDX_DMLA.sql
@C:\work\EltesoftLocal\obh_test\NDX_LGTBL6.sql
@C:\work\EltesoftLocal\obh_test\PK_DM_ANALYSIS_MET.sql
@C:\work\EltesoftLocal\obh_test\NDX_IP_EPIID.sql
@C:\work\EltesoftLocal\obh_test\PK_EPI_TREATM_PARAM.sql
@C:\work\EltesoftLocal\obh_test\NDX_EPIS2.sql
@C:\work\EltesoftLocal\obh_test\TREATM_REL_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\PRT_TREATM_REL_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\GIS_SUBJ_EPI_REL_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DATA_INCO_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE_RIGHT_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_MESSAGE_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\EPI_PARAM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_COUNTRY_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TREATM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TRAFFIC_SUM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\LOG_TABLE_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DEV_TEMP_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\EPI_REL_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_XL_REL_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_REGULATION_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\PRT_IC_ITEM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\SUBJ_REL_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\USERS_DEFAULTS_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\INVENT_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\ALERT_PARAM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\PRT_TREATM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_CAT_USAGE_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_SUPER_TYP_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\GIS_REL_PARAM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_CURRENCY_CHANGE_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\GIS_DATA_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_USER_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\APEX_MENU_TEMP_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PARAM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\GIS_DATA_REL_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\ALERT_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\SUBJ_PARAM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\PRT_IC_HEAD_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_TRANSLATE_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_ANALYSIS_TYP_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_VER_INFO_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TIME_TABLE_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_SALUTATION_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_DBA_LOG_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TREATM_COPY_TEMP_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\EPI_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\VERSION_INFO_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\SUBJECT_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\EPI_TREATM_PARAM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_AVC_LOG_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TR_XL_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\PRT_WORK_TIME_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_NAMES_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_TEXT_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PRU_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\INVENT_PARAM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\VALID_UNIT_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_CHG_LOG_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_ANALYSIS_MET_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\MM_FILES_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\EPI_TREATM_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_LANGUAGE_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_EVAL_LOG_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE_USER_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\CELL_COMMENTS_CONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\ALERT_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\ALERT_PARAM_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DATA_INCO_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_ANALYSIS_TYP_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_MESSAGE_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_NAMES_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_REGULATION_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE_RIGHT_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_ROLE_USER_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\DM_USER_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\EPI_REL_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\EPI_TREATM_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\GIS_REL_PARAM_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\INVENT_PARAM_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\MM_FILES_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\PRT_IC_HEAD_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\PRT_IC_ITEM_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\PRT_WORK_TIME_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\SUBJECT_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\SUBJ_PARAM_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\SUBJ_REL_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TIME_TABLE_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TRAFFIC_SUM_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TREATM_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\TREATM_REL_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\USERS_DEFAULTS_REFCONSTRAINT.sql
@C:\work\EltesoftLocal\obh_test\LTRG_DM_ANALYSIS_TYP.sql
@C:\work\EltesoftLocal\obh_test\LTRG_DM_CAT_USAGE.sql
@C:\work\EltesoftLocal\obh_test\LTRG_DM_COUNTRY.sql
@C:\work\EltesoftLocal\obh_test\LTRG_DM_LANGUAGE.sql
@C:\work\EltesoftLocal\obh_test\LTRG_DM_MESSAGE.sql
@C:\work\EltesoftLocal\obh_test\LTRG_DM_REGULATION.sql
@C:\work\EltesoftLocal\obh_test\LTRG_DM_ROLE.sql
@C:\work\EltesoftLocal\obh_test\LTRG_DM_SALUTATION.sql
@C:\work\EltesoftLocal\obh_test\LTRG_DM_USER.sql
@C:\work\EltesoftLocal\obh_test\LTRG_EPI.sql
@C:\work\EltesoftLocal\obh_test\LTRG_EPI_SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\LTRG_EPI_TREATM_PARAM.sql
@C:\work\EltesoftLocal\obh_test\LTRG_GIS_DATA.sql
@C:\work\EltesoftLocal\obh_test\LTRG_GIS_DATA_REL.sql
@C:\work\EltesoftLocal\obh_test\LTRG_GIS_REL_PARAM.sql
@C:\work\EltesoftLocal\obh_test\LTRG_GIS_SUBJ_EPI_REL.sql
@C:\work\EltesoftLocal\obh_test\LTRG_INVENT.sql
@C:\work\EltesoftLocal\obh_test\LTRG_MM_FILES.sql
@C:\work\EltesoftLocal\obh_test\LTRG_PRT_IC_HEAD.sql
@C:\work\EltesoftLocal\obh_test\LTRG_PRT_TREATM_REL.sql
@C:\work\EltesoftLocal\obh_test\LTRG_SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\LTRG_TIME_TABLE.sql
@C:\work\EltesoftLocal\obh_test\LTRG_TREATM.sql
@C:\work\EltesoftLocal\obh_test\LTRG_VERSION_INFO.sql
@C:\work\EltesoftLocal\obh_test\TRG_ADMIN_CHG_LOG.sql
@C:\work\EltesoftLocal\obh_test\TRG_ADMIN_DBA_LOG.sql
@C:\work\EltesoftLocal\obh_test\TRG_ADMIN_EVAL_LOG.sql
@C:\work\EltesoftLocal\obh_test\TRG_ALERT.sql
@C:\work\EltesoftLocal\obh_test\TRG_ALERT_PARAM.sql
@C:\work\EltesoftLocal\obh_test\TRG_CELL_COMMENTS.sql
@C:\work\EltesoftLocal\obh_test\TRG_DM_ROLE_USER.sql
@C:\work\EltesoftLocal\obh_test\TRG_DM_SUPER_TYP.sql
@C:\work\EltesoftLocal\obh_test\TRG_DM_TREATM.sql
@C:\work\EltesoftLocal\obh_test\TRG_DM_XL.sql
@C:\work\EltesoftLocal\obh_test\TRG_DM_XL_REL.sql
@C:\work\EltesoftLocal\obh_test\TRG_EPI_REL.sql
@C:\work\EltesoftLocal\obh_test\TRG_EPI_SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\TRG_SUBJECT.sql
@C:\work\EltesoftLocal\obh_test\TRG_SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\TRG_SUBJ_REL.sql
@C:\work\EltesoftLocal\obh_test\TRG_TRAFFIC_SUM.sql
@C:\work\EltesoftLocal\obh_test\TRG_TREATM_PARAM.sql
@C:\work\EltesoftLocal\obh_test\TRG_TREATM_REL.sql
@C:\work\EltesoftLocal\obh_test\TRG_TR_XL.sql
@C:\work\EltesoftLocal\obh_test\TRG_TR_XL_LOAD_ERROR.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_ANALYSIS_TYP.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_CAT_USAGE.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_COUNTRY.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_CURRENCY_CHANGE.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_LANGUAGE.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_MESSAGE.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_NAMES.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_REGULATION.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_ROLE.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_SALUTATION.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_TEXT.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_TRANSLATE.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_TREATM_PRU.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_UNIT.sql
@C:\work\EltesoftLocal\obh_test\TRG2_DM_USER.sql
@C:\work\EltesoftLocal\obh_test\TRG2_EPI.sql
@C:\work\EltesoftLocal\obh_test\TRG2_EPI_INVENT.sql
@C:\work\EltesoftLocal\obh_test\TRG2_EPI_INVENT_PARAM.sql
@C:\work\EltesoftLocal\obh_test\TRG2_EPI_REL.sql
@C:\work\EltesoftLocal\obh_test\TRG2_EPI_TREATM.sql
@C:\work\EltesoftLocal\obh_test\TRG2_EPI_TREATM_PARAM.sql
@C:\work\EltesoftLocal\obh_test\TRG2_GIS_DATA.sql
@C:\work\EltesoftLocal\obh_test\TRG2_GIS_REL_PARAM.sql
@C:\work\EltesoftLocal\obh_test\TRG2_MM_FILES.sql
@C:\work\EltesoftLocal\obh_test\TRG2_PRT_IC_HEAD.sql
@C:\work\EltesoftLocal\obh_test\TRG2_PRT_IC_ITEM.sql
@C:\work\EltesoftLocal\obh_test\TRG2_PRT_TREATM.sql
@C:\work\EltesoftLocal\obh_test\TRG2_PRT_TREATM_REL.sql
@C:\work\EltesoftLocal\obh_test\TRG2_SUBJ_PARAM.sql
@C:\work\EltesoftLocal\obh_test\TRG2_TIME_TABLE.sql
@C:\work\EltesoftLocal\obh_test\TRG2_USERS_DEFAULTS.sql
@C:\work\EltesoftLocal\obh_test\TRG2_VALID_UNIT.sql
@C:\work\EltesoftLocal\obh_test\TRG2_VERSION_INFO.sql
@C:\work\EltesoftLocal\obh_test\TRG2_WK_TIME.sql
@C:\work\EltesoftLocal\obh_test\BREAK_STRING.sql
@C:\work\EltesoftLocal\obh_test\CALCULATE_COL_VALUE.sql
@C:\work\EltesoftLocal\obh_test\CALCULATE_ROW_VALUE.sql
@C:\work\EltesoftLocal\obh_test\CAN_EDIT_SUPER_TYP.sql
@C:\work\EltesoftLocal\obh_test\COLUMN_HEAD.sql
@C:\work\EltesoftLocal\obh_test\COLUMN_SHOW.sql
@C:\work\EltesoftLocal\obh_test\COPY_DOC.sql
@C:\work\EltesoftLocal\obh_test\CUSTOM_HASH.sql
@C:\work\EltesoftLocal\obh_test\DM_TRANSLATE_F.sql
@C:\work\EltesoftLocal\obh_test\FUNCTION1.sql
@C:\work\EltesoftLocal\obh_test\FUNCTION2.sql
@C:\work\EltesoftLocal\obh_test\GET_APEX_LINK.sql
@C:\work\EltesoftLocal\obh_test\GET_APEX_USER_ID.sql
@C:\work\EltesoftLocal\obh_test\GET_COLUMN_HEAD_STRING.sql
@C:\work\EltesoftLocal\obh_test\GET_DM_XL_ID_TO.sql
@C:\work\EltesoftLocal\obh_test\GET_DOC_DEFAULT_LIST.sql
@C:\work\EltesoftLocal\obh_test\GET_DOC_EDIT_HTML.sql
@C:\work\EltesoftLocal\obh_test\GET_DOC_ID.sql
@C:\work\EltesoftLocal\obh_test\GET_ELOIR_HTML.sql
@C:\work\EltesoftLocal\obh_test\GET_INTERVALL_DAYS.sql
@C:\work\EltesoftLocal\obh_test\GET_NEXT_ID.sql
@C:\work\EltesoftLocal\obh_test\GET_SUBJ_ID.sql
@C:\work\EltesoftLocal\obh_test\GET_SUPER_TYP_GROUP_ID.sql
@C:\work\EltesoftLocal\obh_test\GET_TREATM_CREATE_BTN_TEXT.sql
@C:\work\EltesoftLocal\obh_test\GET_TREATM_REGION_HEADER_TEXT.sql
@C:\work\EltesoftLocal\obh_test\GET_USER_ID.sql
@C:\work\EltesoftLocal\obh_test\INSERT_TR_XL_ROW.sql
@C:\work\EltesoftLocal\obh_test\LOOKUP_MENU_LABEL.sql
@C:\work\EltesoftLocal\obh_test\LOOKUP_SUBJ_NAME.sql
@C:\work\EltesoftLocal\obh_test\LOOKUP_SUPER_TYPE_DESCRIPTION.sql
@C:\work\EltesoftLocal\obh_test\LOOKUP_SUPER_TYPE_GROUP_ID.sql
@C:\work\EltesoftLocal\obh_test\LOOKUP_SUPER_TYPE_NAME.sql
@C:\work\EltesoftLocal\obh_test\LOOKUP_TR_XL_VALUE.sql
@C:\work\EltesoftLocal\obh_test\MENU_RIGHT.sql
@C:\work\EltesoftLocal\obh_test\REV_LOOKUP_SUPER_TYPE_NAME_EX.sql
@C:\work\EltesoftLocal\obh_test\SEARCH_GROUND_LEVEL_ID.sql
@C:\work\EltesoftLocal\obh_test\SUM_COL_VALUE.sql
@C:\work\EltesoftLocal\obh_test\TREATMENT_IS_IN_TREE.sql
@C:\work\EltesoftLocal\obh_test\USER_IS_IN_ROLE.sql
@C:\work\EltesoftLocal\obh_test\USER_PAGE_RIGHT.sql
@C:\work\EltesoftLocal\obh_test\USER_ROLE_LEVEL.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_PKG.sql
@C:\work\EltesoftLocal\obh_test\APEX_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\BASE_PKG.sql
@C:\work\EltesoftLocal\obh_test\CSV_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\DATAPUMP_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\DATE_INTERVALL.sql
@C:\work\EltesoftLocal\obh_test\DATE_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\DEBUG_PKG.sql
@C:\work\EltesoftLocal\obh_test\DM_XL_REL_TAPI.sql
@C:\work\EltesoftLocal\obh_test\DM_XL_TAPI.sql
@C:\work\EltesoftLocal\obh_test\ENCODE_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\FILE_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\FLEX_WS_API.sql
@C:\work\EltesoftLocal\obh_test\FTP_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\GENERATE_HTML.sql
@C:\work\EltesoftLocal\obh_test\GIS_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\GOOGLE_MAPS_PKG.sql
@C:\work\EltesoftLocal\obh_test\GOOGLE_TRANSLATE_PKG.sql
@C:\work\EltesoftLocal\obh_test\HTML_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\HTTP_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\ICALENDAR_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\IMAGE_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\JSON_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\MATH_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\MS_EWS_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\OOXML_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\OWA_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\PDF_BUILDER_PKG.sql
@C:\work\EltesoftLocal\obh_test\PKG_INVENT.sql
@C:\work\EltesoftLocal\obh_test\PKG_ROLE.sql
@C:\work\EltesoftLocal\obh_test\RANDOM_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\RAW_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\REGEXP_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\RSS_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\SOAP_SERVER_PKG.sql
@C:\work\EltesoftLocal\obh_test\SQL_BUILDER_PKG.sql
@C:\work\EltesoftLocal\obh_test\SQL_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\STRING_FNC.sql
@C:\work\EltesoftLocal\obh_test\STRING_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\SYLK_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PARAM_TAPI.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PRU_TAPI.sql
@C:\work\EltesoftLocal\obh_test\TREATM_REL_TAPI.sql
@C:\work\EltesoftLocal\obh_test\TREATM_TAPI.sql
@C:\work\EltesoftLocal\obh_test\URI_TEMPLATE_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\VALIDATION_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\WEB_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\XLSX_BUILDER_PKG.sql
@C:\work\EltesoftLocal\obh_test\XML_BUILDER_PKG.sql
@C:\work\EltesoftLocal\obh_test\XML_DATASET_PKG.sql
@C:\work\EltesoftLocal\obh_test\XML_STYLESHEET_PKG.sql
@C:\work\EltesoftLocal\obh_test\XML_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\ZIP_UTIL_PKG.sql
@C:\work\EltesoftLocal\obh_test\ADMIN_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\APEX_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\BASE_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\CSV_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\DATAPUMP_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\DATE_INTERVALL_1.sql
@C:\work\EltesoftLocal\obh_test\DATE_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\DEBUG_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\DM_XL_REL_TAPI_1.sql
@C:\work\EltesoftLocal\obh_test\DM_XL_TAPI_1.sql
@C:\work\EltesoftLocal\obh_test\ENCODE_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\FILE_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\FLEX_WS_API_1.sql
@C:\work\EltesoftLocal\obh_test\FTP_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\GENERATE_HTML_1.sql
@C:\work\EltesoftLocal\obh_test\GIS_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\GOOGLE_MAPS_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\GOOGLE_TRANSLATE_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\HTML_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\HTTP_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\ICALENDAR_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\IMAGE_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\INTEGRITYPACKAGE.sql
@C:\work\EltesoftLocal\obh_test\JSON_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\MATH_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\MS_EWS_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\OOXML_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\OWA_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\PDF_BUILDER_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\PKG_INVENT_1.sql
@C:\work\EltesoftLocal\obh_test\PKG_ROLE_1.sql
@C:\work\EltesoftLocal\obh_test\RANDOM_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\RAW_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\REGEXP_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\RSS_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\SOAP_SERVER_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\SQL_BUILDER_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\SQL_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\STRING_FNC_1.sql
@C:\work\EltesoftLocal\obh_test\STRING_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\SYLK_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PARAM_TAPI_1.sql
@C:\work\EltesoftLocal\obh_test\TREATM_PRU_TAPI_1.sql
@C:\work\EltesoftLocal\obh_test\TREATM_REL_TAPI_1.sql
@C:\work\EltesoftLocal\obh_test\TREATM_TAPI_1.sql
@C:\work\EltesoftLocal\obh_test\URI_TEMPLATE_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\VALIDATION_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\WEB_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\XLSX_BUILDER_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\XML_BUILDER_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\XML_DATASET_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\XML_STYLESHEET_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\XML_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\ZIP_UTIL_PKG_1.sql
@C:\work\EltesoftLocal\obh_test\BULK_LOAD_FROM_BLOB.sql
@C:\work\EltesoftLocal\obh_test\CALCULATE_SHEET.sql
@C:\work\EltesoftLocal\obh_test\CPY_DM_XL_DOC.sql
@C:\work\EltesoftLocal\obh_test\CPY_DM_XL_LIST.sql
@C:\work\EltesoftLocal\obh_test\CREATE_ADAT_BEERKEZES.sql
@C:\work\EltesoftLocal\obh_test\CREATE_REPORT.sql
@C:\work\EltesoftLocal\obh_test\CREATE_T.sql
@C:\work\EltesoftLocal\obh_test\DO_SYSTEM_TASK.sql
@C:\work\EltesoftLocal\obh_test\IMAGE_DISPLAY.sql
@C:\work\EltesoftLocal\obh_test\INSERT_TR_XL_REC.sql
@C:\work\EltesoftLocal\obh_test\LOAD_TRAFFIC_SUM_FROM_TR_XL.sql
@C:\work\EltesoftLocal\obh_test\LOAD_TR_XL_FROM_BLOB.sql
@C:\work\EltesoftLocal\obh_test\PREPARE_CONTROL.sql
@C:\work\EltesoftLocal\obh_test\RELOAD_FROM_BLOB.sql
@C:\work\EltesoftLocal\obh_test\RELOAD_TR_XL.sql
@C:\work\EltesoftLocal\obh_test\SEND_ALERT.sql
@C:\work\EltesoftLocal\obh_test\SEND_ALERT_CTE.sql
@C:\work\EltesoftLocal\obh_test\SET_TR_XL_PARAM_VALUE.sql
@C:\work\EltesoftLocal\obh_test\SHOWBLOB.sql
@C:\work\EltesoftLocal\obh_test\TR_XL_INSERT_OR_UPDATE.sql
