--------------------------------------------------------
--  DDL for Trigger LTRG_DM_LANGUAGE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "LTRG_DM_LANGUAGE" 
AFTER INSERT OR UPDATE OR DELETE ON AMNIS.DM_LANGUAGE FOR EACH ROW
DECLARE
BEGIN
BEGIN
DECLARE
V_TNAME VARCHAR2(30) := 'DM_LANGUAGE';
VALUE_EX EXCEPTION;
INSERT_EXC EXCEPTION;
BEGIN
IF updating THEN
BEGIN
IF   (:new.LANGUAGE_ID IS NULL AND :old.LANGUAGE_ID IS NOT NULL)
  OR (:new.LANGUAGE_ID IS NOT NULL AND :old.LANGUAGE_ID IS NULL)
  OR (:new.LANGUAGE_ID != :old.LANGUAGE_ID) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'LANGUAGE_ID',:old.LANGUAGE_ID,:new.LANGUAGE_ID,v('EPI_ID') );
END IF;
IF   (:new.LANGUAGE_NAME IS NULL AND :old.LANGUAGE_NAME IS NOT NULL)
  OR (:new.LANGUAGE_NAME IS NOT NULL AND :old.LANGUAGE_NAME IS NULL)
  OR (:new.LANGUAGE_NAME != :old.LANGUAGE_NAME) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'LANGUAGE_NAME',:old.LANGUAGE_NAME,:new.LANGUAGE_NAME,v('EPI_ID') );
END IF;
IF   (:new.LANGUAGE_TYP IS NULL AND :old.LANGUAGE_TYP IS NOT NULL)
  OR (:new.LANGUAGE_TYP IS NOT NULL AND :old.LANGUAGE_TYP IS NULL)
  OR (:new.LANGUAGE_TYP != :old.LANGUAGE_TYP) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'LANGUAGE_TYP',:old.LANGUAGE_TYP,:new.LANGUAGE_TYP,v('EPI_ID') );
END IF;
IF   (:new.RL IS NULL AND :old.RL IS NOT NULL)
  OR (:new.RL IS NOT NULL AND :old.RL IS NULL)
  OR (:new.RL != :old.RL) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'RL',:old.RL,:new.RL,v('EPI_ID') );
END IF;
IF   (:new.DESCRIPTION IS NULL AND :old.DESCRIPTION IS NOT NULL)
  OR (:new.DESCRIPTION IS NOT NULL AND :old.DESCRIPTION IS NULL)
  OR (:new.DESCRIPTION != :old.DESCRIPTION) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'DESCRIPTION',:old.DESCRIPTION,:new.DESCRIPTION,v('EPI_ID') );
END IF;
IF   (:new.FROM_DATE IS NULL AND :old.FROM_DATE IS NOT NULL)
  OR (:new.FROM_DATE IS NOT NULL AND :old.FROM_DATE IS NULL)
  OR (:new.FROM_DATE != :old.FROM_DATE) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'FROM_DATE',:old.FROM_DATE,:new.FROM_DATE,v('EPI_ID') );
END IF;
IF   (:new.TO_DATE IS NULL AND :old.TO_DATE IS NOT NULL)
  OR (:new.TO_DATE IS NOT NULL AND :old.TO_DATE IS NULL)
  OR (:new.TO_DATE != :old.TO_DATE) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'TO_DATE',:old.TO_DATE,:new.TO_DATE,v('EPI_ID') );
END IF;
IF   (:new.CRU IS NULL AND :old.CRU IS NOT NULL)
  OR (:new.CRU IS NOT NULL AND :old.CRU IS NULL)
  OR (:new.CRU != :old.CRU) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'CRU',:old.CRU,:new.CRU,v('EPI_ID') );
END IF;
IF   (:new.MDU IS NULL AND :old.MDU IS NOT NULL)
  OR (:new.MDU IS NOT NULL AND :old.MDU IS NULL)
  OR (:new.MDU != :old.MDU) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'MDU',:old.MDU,:new.MDU,v('EPI_ID') );
END IF;
IF   (:new.LANGUAGE_CODE IS NULL AND :old.LANGUAGE_CODE IS NOT NULL)
  OR (:new.LANGUAGE_CODE IS NOT NULL AND :old.LANGUAGE_CODE IS NULL)
  OR (:new.LANGUAGE_CODE != :old.LANGUAGE_CODE) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'LANGUAGE_CODE',:old.LANGUAGE_CODE,:new.LANGUAGE_CODE,v('EPI_ID') );
END IF;
IF   (:new.W_COUNTRY_TRICODE IS NULL AND :old.W_COUNTRY_TRICODE IS NOT NULL)
  OR (:new.W_COUNTRY_TRICODE IS NOT NULL AND :old.W_COUNTRY_TRICODE IS NULL)
  OR (:new.W_COUNTRY_TRICODE != :old.W_COUNTRY_TRICODE) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'W_COUNTRY_TRICODE',:old.W_COUNTRY_TRICODE,:new.W_COUNTRY_TRICODE,v('EPI_ID') );
END IF;
IF   (:new.ISO639_3 IS NULL AND :old.ISO639_3 IS NOT NULL)
  OR (:new.ISO639_3 IS NOT NULL AND :old.ISO639_3 IS NULL)
  OR (:new.ISO639_3 != :old.ISO639_3) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'ISO639_3',:old.ISO639_3,:new.ISO639_3,v('EPI_ID') );
END IF;
IF   (:new.ISO639_2 IS NULL AND :old.ISO639_2 IS NOT NULL)
  OR (:new.ISO639_2 IS NOT NULL AND :old.ISO639_2 IS NULL)
  OR (:new.ISO639_2 != :old.ISO639_2) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'ISO639_2',:old.ISO639_2,:new.ISO639_2,v('EPI_ID') );
END IF;
IF   (:new.ISO639_1 IS NULL AND :old.ISO639_1 IS NOT NULL)
  OR (:new.ISO639_1 IS NOT NULL AND :old.ISO639_1 IS NULL)
  OR (:new.ISO639_1 != :old.ISO639_1) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'ISO639_1',:old.ISO639_1,:new.ISO639_1,v('EPI_ID') );
END IF;
IF   (:new.HUN_NAME IS NULL AND :old.HUN_NAME IS NOT NULL)
  OR (:new.HUN_NAME IS NOT NULL AND :old.HUN_NAME IS NULL)
  OR (:new.HUN_NAME != :old.HUN_NAME) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'HUN_NAME',:old.HUN_NAME,:new.HUN_NAME,v('EPI_ID') );
END IF;
IF   (:new.ENG_NAME IS NULL AND :old.ENG_NAME IS NOT NULL)
  OR (:new.ENG_NAME IS NOT NULL AND :old.ENG_NAME IS NULL)
  OR (:new.ENG_NAME != :old.ENG_NAME) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'ENG_NAME',:old.ENG_NAME,:new.ENG_NAME,v('EPI_ID') );
END IF;
IF   (:new.STATUS_ID IS NULL AND :old.STATUS_ID IS NOT NULL)
  OR (:new.STATUS_ID IS NOT NULL AND :old.STATUS_ID IS NULL)
  OR (:new.STATUS_ID != :old.STATUS_ID) THEN 
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'U',admin_pkg.apex_user,
'STATUS_ID',:old.STATUS_ID,:new.STATUS_ID,v('EPI_ID') );
END IF;
EXCEPTION
WHEN VALUE_ERROR THEN RAISE VALUE_EX;
WHEN OTHERS THEN RAISE INSERT_EXC;
END;
END IF;
IF deleting THEN
BEGIN
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'LANGUAGE_ID',:old.LANGUAGE_ID,:new.LANGUAGE_ID,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'LANGUAGE_NAME',:old.LANGUAGE_NAME,:new.LANGUAGE_NAME,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'LANGUAGE_TYP',:old.LANGUAGE_TYP,:new.LANGUAGE_TYP,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'RL',:old.RL,:new.RL,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'DESCRIPTION',:old.DESCRIPTION,:new.DESCRIPTION,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'FROM_DATE',:old.FROM_DATE,:new.FROM_DATE,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'TO_DATE',:old.TO_DATE,:new.TO_DATE,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'CRU',:old.CRU,:new.CRU,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'MDU',:old.MDU,:new.MDU,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'LANGUAGE_CODE',:old.LANGUAGE_CODE,:new.LANGUAGE_CODE,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'W_COUNTRY_TRICODE',:old.W_COUNTRY_TRICODE,:new.W_COUNTRY_TRICODE,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'ISO639_3',:old.ISO639_3,:new.ISO639_3,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'ISO639_2',:old.ISO639_2,:new.ISO639_2,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'ISO639_1',:old.ISO639_1,:new.ISO639_1,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'HUN_NAME',:old.HUN_NAME,:new.HUN_NAME,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'ENG_NAME',:old.ENG_NAME,:new.ENG_NAME,v('EPI_ID') );
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:old.LANGUAGE_ID,'D',admin_pkg.apex_user,
'STATUS_ID',:old.STATUS_ID,:new.STATUS_ID,v('EPI_ID') );
EXCEPTION
WHEN VALUE_ERROR THEN RAISE VALUE_EX;
WHEN OTHERS THEN RAISE INSERT_EXC;
END;
END IF;
IF inserting THEN
BEGIN
INSERT INTO LOG_TABLE
(LOG_ID, OPERATION_TIME, TABLE_NAME,
 RECORD_ID, OPERATION_TYPE, USER_NAME,
 COLUMN_NAME, OLD_VALUE, NEW_VALUE,EPI_ID)
VALUES
(SEQ_LTRG_ID.nextval,sysdate,V_TNAME,
:new.LANGUAGE_ID,'I',admin_pkg.apex_user,
null,null,null,v('EPI_ID') );
EXCEPTION
WHEN VALUE_ERROR THEN RAISE VALUE_EX;
WHEN OTHERS THEN RAISE INSERT_EXC;
END;
END IF;
EXCEPTION
WHEN VALUE_EX THEN
raise_application_error(-20201,'Value error on LOG_TABLE insert:');
WHEN INSERT_EXC THEN
raise_application_error(-20202,'Error on LOG_TABLE insert!');
END;
END;
END;
/
ALTER TRIGGER "LTRG_DM_LANGUAGE" ENABLE;
