--------------------------------------------------------
--  DDL for Table MM_FILES
--------------------------------------------------------

  CREATE TABLE "MM_FILES" 
   (	"MM_ID" NUMBER(12,0), 
	"MM_TYPE_ID" NUMBER(12,0), 
	"EPI_ID" NUMBER(12,0), 
	"MM_HYPL" VARCHAR2(255 BYTE), 
	"MM_BLOB" BLOB, 
	"MAIN_TYPE" VARCHAR2(30 BYTE), 
	"FILE_NAME" VARCHAR2(255 BYTE), 
	"MM_CHARSET" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(255 BYTE), 
	"CRU" VARCHAR2(30 BYTE), 
	"CRD" TIMESTAMP (6) DEFAULT SYSDATE, 
	"MDU" VARCHAR2(30 BYTE), 
	"MDD" TIMESTAMP (6), 
	"TITLE" VARCHAR2(255 BYTE), 
	"SUBJ_ID" NUMBER(12,0), 
	"STAT_TYPE_ID" NUMBER(12,0) DEFAULT 5, 
	"STATUS_ID" NUMBER(12,0) DEFAULT 912
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("MM_BLOB") STORE AS BASICFILE (
  TABLESPACE "DENT_MDB" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
 

   COMMENT ON COLUMN "MM_FILES"."MM_ID" IS 'Documentum egyedi azonosítója';
 
   COMMENT ON COLUMN "MM_FILES"."MM_TYPE_ID" IS 'Multimedia Típusának azonosítója';
 
   COMMENT ON COLUMN "MM_FILES"."EPI_ID" IS 'Kapcsolódó esemény egyedi azonosítója';
 
   COMMENT ON COLUMN "MM_FILES"."MM_HYPL" IS 'Documentum file linkje';
 
   COMMENT ON COLUMN "MM_FILES"."MM_BLOB" IS 'Multimédia Bináris fájlja';
 
   COMMENT ON COLUMN "MM_FILES"."MAIN_TYPE" IS 'Fájl típusa, kterjesztése';
 
   COMMENT ON COLUMN "MM_FILES"."FILE_NAME" IS 'Fájl neve';
 
   COMMENT ON COLUMN "MM_FILES"."MM_CHARSET" IS 'Dokumentum karakterkészlete';
 
   COMMENT ON COLUMN "MM_FILES"."DESCRIPTION" IS 'Leírás';
 
   COMMENT ON COLUMN "MM_FILES"."CRU" IS 'Rekord Létrehozójának Azonosítója';
 
   COMMENT ON COLUMN "MM_FILES"."CRD" IS 'Rekord Létrehozásának időpecsétje';
 
   COMMENT ON COLUMN "MM_FILES"."MDU" IS 'Rekord Módosítójának Azonosítója';
 
   COMMENT ON COLUMN "MM_FILES"."MDD" IS 'Rekord Módosításának Időpecsétje';
 
   COMMENT ON COLUMN "MM_FILES"."TITLE" IS 'Multimedia címe';
 
   COMMENT ON COLUMN "MM_FILES"."SUBJ_ID" IS 'A dokumentumhoz tartozó alany';
 
   COMMENT ON COLUMN "MM_FILES"."STAT_TYPE_ID" IS 'Feldolgozottsági állapot státusz típusának egyedi azonosítója';
 
   COMMENT ON COLUMN "MM_FILES"."STATUS_ID" IS 'Feldolgozottsági állapot státusz típusának egyedi azonosítója';
 
   COMMENT ON TABLE "MM_FILES"  IS 'Multimedia letárolási helyei
Code: MMFS';
