--------------------------------------------------------
--  DDL for Index NDX_TIMT_1
--------------------------------------------------------

  CREATE INDEX "NDX_TIMT_1" ON "TIME_TABLE" ("TT_START", "TT_END") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
