--------------------------------------------------------
--  DDL for Index NDX_DMTR_1
--------------------------------------------------------

  CREATE INDEX "NDX_DMTR_1" ON "DM_TRANSLATE" ("TBL_NAME", "TBL_COL_NAME", "TBL_PK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DENT_NDX" ;
