--------------------------------------------------------
--  Ref Constraints for Table TREATM
--------------------------------------------------------

  ALTER TABLE "TREATM" ADD CONSTRAINT "FK_TRTM_DSRT_STATTYP" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "DM_SUPER_TYP" ("SUPER_TYP_ID") ENABLE;
 
  ALTER TABLE "TREATM" ADD CONSTRAINT "FK_TRTM_DSRT_TRTTYID" FOREIGN KEY ("TREATM_TYPE_ID")
	  REFERENCES "DM_SUPER_TYP" ("SUPER_TYP_ID") DISABLE;
 
  ALTER TABLE "TREATM" ADD CONSTRAINT "FK_TRTM_DSRT_TYID1" FOREIGN KEY ("TYPE1_ID")
	  REFERENCES "DM_SUPER_TYP" ("SUPER_TYP_ID") ENABLE;
 
  ALTER TABLE "TREATM" ADD CONSTRAINT "FK_TRTM_DSRT_TYID2" FOREIGN KEY ("TYPE2_ID")
	  REFERENCES "DM_SUPER_TYP" ("SUPER_TYP_ID") ENABLE;
