--------------------------------------------------------
--  DDL for Trigger TRG2_DM_ANALYSIS_TYP
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_DM_ANALYSIS_TYP" 
BEFORE INSERT OR UPDATE ON AMNIS.DM_ANALYSIS_MET FOR EACH ROW
BEGIN
IF INSERTING THEN
IF 
 :NEW.ANALYSIS_MET_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL 
 INTO :NEW.ANALYSIS_MET_ID FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=BASE_PKG.V_USER;       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING THEN 
  :NEW.MDD:=SYSTIMESTAMP;	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=BASE_PKG.V_USER;       --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG2_DM_ANALYSIS_TYP" ENABLE;
