--------------------------------------------------------
--  DDL for Trigger TRG2_GIS_DATA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_GIS_DATA" 
BEFORE INSERT ON AMNIS.GIS_DATA FOR EACH ROW
BEGIN
IF INSERTING THEN
IF 
 :NEW.GIS_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL 
 INTO :NEW.GIS_ID FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=BASE_PKG.V_USER;       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING THEN 
  :NEW.MDD:=SYSTIMESTAMP;	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=BASE_PKG.V_USER;       --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG2_GIS_DATA" ENABLE;
