--------------------------------------------------------
--  DDL for Trigger TRG2_DM_USER
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_DM_USER" 
BEFORE INSERT OR UPDATE ON AMNIS.DM_USER FOR EACH ROW
BEGIN
IF INSERTING THEN
 IF 
 :NEW.USER_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL 
 INTO :NEW.USER_ID FROM DUAL;
 END IF;
 :NEW.CRD:=SYSTIMESTAMP;     --LÉTREHOZÁS IDŐPONTJA
 :NEW.CRU:=(NVL(V('APP_USER'),USER));       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING THEN 
--IF :NEW.ACT_ID IS NOT NULL AND :NEW.CRU IS NOT NULL THEN
  :NEW.MDD:=SYSTIMESTAMP;      --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=(NVL(V('APP_USER'),USER));       --APEX USER AKI MÓDOSÍT
--END IF;
END IF;
END;
/
ALTER TRIGGER "TRG2_DM_USER" ENABLE;
