--------------------------------------------------------
--  DDL for Trigger TRG2_DM_CAT_USAGE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_DM_CAT_USAGE" 
BEFORE INSERT ON AMNIS.DM_CAT_USAGE FOR EACH ROW
BEGIN
IF INSERTING THEN
IF 
 :NEW.CAT_USAGE_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL 
 INTO :NEW.CAT_USAGE_ID FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=BASE_PKG.V_USER;       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING THEN 
  :NEW.MDD:=SYSTIMESTAMP;	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=BASE_PKG.V_USER;       --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG2_DM_CAT_USAGE" ENABLE;
