--------------------------------------------------------
--  DDL for Trigger TRG2_DM_CURRENCY_CHANGE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_DM_CURRENCY_CHANGE" 
BEFORE INSERT OR UPDATE ON AMNIS.DM_CURRENCY_CHANGE FOR EACH ROW
BEGIN
IF INSERTING THEN
 IF 
 :NEW.CURR_CHANG_ID IS NULL THEN
  SELECT SEQ_NEW.NEXTVAL 
 INTO :NEW.CURR_CHANG_ID FROM DUAL;
 END IF;
 :NEW.CRD:=SYSTIMESTAMP;            --LÉTREHOZÁS IDŐPONTJA
 :NEW.CRU:=BASE_PKG.V_USER;       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING THEN 
  :NEW.MDD:=SYSTIMESTAMP;           --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=BASE_PKG.V_USER;      --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG2_DM_CURRENCY_CHANGE" ENABLE;
