--------------------------------------------------------
--  DDL for Trigger TRG2_SUBJ_PARAM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_SUBJ_PARAM" 
BEFORE INSERT ON AMNIS.SUBJ_PARAM FOR EACH ROW
BEGIN
IF INSERTING THEN
if 
 :NEW.SUBJ_PARAM_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL 
 INTO :NEW.SUBJ_PARAM_ID FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=BASE_PKG.V_USER;       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING THEN 
  :NEW.MDD:=SYSTIMESTAMP;	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=BASE_PKG.V_USER;       --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG2_SUBJ_PARAM" ENABLE;
