--------------------------------------------------------
--  DDL for Trigger TRG2_EPI_INVENT_PARAM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_EPI_INVENT_PARAM" 
BEFORE INSERT ON AMNIS.INVENT_PARAM FOR EACH ROW
declare
pragma autonomous_transaction;
BEGIN
IF INSERTING THEN
IF 
 :NEW.INVENT_PARAM_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL 
 INTO :NEW.INVENT_PARAM_ID FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=BASE_PKG.V_USER;       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING
THEN
  :NEW.MDD:=SYSTIMESTAMP;	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=BASE_PKG.V_USER;       --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG2_EPI_INVENT_PARAM" ENABLE;
