--------------------------------------------------------
--  DDL for Trigger TRG2_EPI_INVENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_EPI_INVENT" 
BEFORE INSERT ON AMNIS.INVENT FOR EACH ROW
BEGIN
IF INSERTING THEN
IF 
 :NEW.INVENT_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL 
 INTO :NEW.INVENT_ID FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=BASE_PKG.V_USER;       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING
THEN
  :NEW.MDD:=SYSTIMESTAMP;	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=BASE_PKG.V_USER;       --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG2_EPI_INVENT" ENABLE;
