--------------------------------------------------------
--  DDL for Trigger TRG2_DM_LANGUAGE
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_DM_LANGUAGE" 
BEFORE INSERT OR UPDATE ON AMNIS.DM_LANGUAGE FOR EACH ROW
BEGIN
IF INSERTING THEN
IF 
 :NEW.LANGUAGE_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL 
 INTO :NEW.LANGUAGE_ID FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=BASE_PKG.V_USER;       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING
THEN
  :NEW.MDD:=SYSTIMESTAMP;	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=BASE_PKG.V_USER;       --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG2_DM_LANGUAGE" ENABLE;
