--------------------------------------------------------
--  DDL for Trigger TRG2_DM_TEXT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG2_DM_TEXT" 
BEFORE INSERT ON AMNIS.DM_TEXT FOR EACH ROW
BEGIN
IF INSERTING THEN
IF 
 :NEW.DM_TEXT_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL 
 INTO :NEW.DM_TEXT_ID FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=(NVL(V('APP_USER'),USER));       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING THEN 
  :NEW.MDD:=SYSTIMESTAMP;	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=(NVL(V('APP_USER'),USER));       --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG2_DM_TEXT" ENABLE;
