--------------------------------------------------------
--  DDL for Trigger TRG_DM_XL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_DM_XL" 
BEFORE INSERT OR UPDATE ON AMNIS.DM_XL FOR EACH ROW
BEGIN
  IF INSERTING
  THEN
    IF :new.DM_XL_ID IS NULL OR :new.DM_XL_ID = 0
    THEN
SELECT SEQ_BASE.NEXTVAL
  INTO :NEW.DM_XL_ID
  FROM DUAL;
END IF;
    :new.CRD := SYSTIMESTAMP;
      --LÉTREHOZÁS IDŐPONTJA
    :NEW.CRU := NVL(V('APP_USER'), USER);
 --APEX USER AKI LÉTREHOZZA A REKORDOT
  ELSIF UPDATING
  THEN
    :new.MDD := SYSTIMESTAMP;
      --MÓDOSÍTÁS IDŐPONTJA
    :NEW.MDU := NVL(V('APP_USER'), USER);
 --APEX USER AKI MÓDOSÍT
  END IF;
END TRG_DM_XL;
/
ALTER TRIGGER "TRG_DM_XL" ENABLE;
