--------------------------------------------------------
--  DDL for Trigger TRG_CELL_COMMENTS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_CELL_COMMENTS" 
BEFORE INSERT OR UPDATE ON AMNIS.CELL_COMMENTS FOR EACH ROW
BEGIN
IF INSERTING THEN
IF 
 :NEW.CELL_COMMETNT_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL
 INTO :NEW.CELL_COMMETNT_ID FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=NVL(V('APP_USER'),USER);        --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING
THEN
  :NEW.MDD:=SYSTIMESTAMP;	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=NVL(V('APP_USER'),USER);       --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG_CELL_COMMENTS" ENABLE;
