--------------------------------------------------------
--  DDL for Trigger TRG_TR_XL_LOAD_ERROR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_TR_XL_LOAD_ERROR" 
BEFORE INSERT OR UPDATE ON AMNIS.TR_XL_LOAD_ERR FOR EACH ROW
BEGIN
  IF INSERTING
  THEN
    IF :new.TR_XL_ID IS NULL OR :new.TR_XL_ID = 0
    THEN
      SELECT SEQ_BASE.NEXTVAL
        INTO :NEW.TR_XL_ID
        FROM DUAL;
    END IF;
    :new.CRD := SYSTIMESTAMP;      --LÉTREHOZÁS IDŐPONTJA
    :NEW.CRU := NVL(V('APP_USER'), USER); --APEX USER AKI LÉTREHOZZA A REKORDOT
  ELSIF UPDATING
  THEN
    :new.MDD := SYSTIMESTAMP;      --MÓDOSÍTÁS IDŐPONTJA
    :NEW.MDU := NVL(V('APP_USER'), USER); --APEX USER AKI MÓDOSÍT
  END IF;
END TRG_TR_XL_LOAD_ERROR;
/
ALTER TRIGGER "TRG_TR_XL_LOAD_ERROR" ENABLE;
