--------------------------------------------------------
--  DDL for Trigger TRG_TREATM_REL
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_TREATM_REL" 
BEFORE INSERT OR UPDATE ON AMNIS.TREATM_REL FOR EACH ROW
BEGIN
IF INSERTING THEN
IF 
 :NEW.TREATM_REL_ID IS NULL THEN
SELECT SEQ_BASE.NEXTVAL
  INTO :NEW.TREATM_REL_ID
  FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;
		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=NVL(V('APP_USER'),USER);
        --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING
THEN
  :NEW.MDD:=SYSTIMESTAMP;
	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=NVL(V('APP_USER'),USER);
       --APEX USER AKI MÓDOSÍT
END IF;
IF INSERTING or UPDATING THEN
   select KOD into :NEW.KOD1 from TREATM where TREATM_ID = :NEW.TREATM_ID1;
   select KOD into :NEW.KOD2 from TREATM where TREATM_ID = :NEW.TREATM_ID2;
END IF;
END;
/
ALTER TRIGGER "TRG_TREATM_REL" ENABLE;
