--------------------------------------------------------
--  DDL for Trigger TRG_ADMIN_DBA_LOG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_ADMIN_DBA_LOG" 
BEFORE INSERT OR UPDATE ON AMNIS.ADMIN_DBA_LOG FOR EACH ROW
BEGIN
IF INSERTING THEN
 IF 
 :NEW.DBA_LOG_ID IS NULL THEN
  SELECT SEQ_ADMIN.NEXTVAL 
 INTO :NEW.DBA_LOG_ID FROM DUAL;
 END IF;
 :NEW.TIME_STAMP:=SYSTIMESTAMP;            --LÉTREHOZÁS IDŐPONTJA
 ELSIF UPDATING THEN 
  :NEW.TIME_STAMP:=SYSTIMESTAMP;           --MÓDOSÍTÁS IDŐPONTJA
 END IF;
END;
/
ALTER TRIGGER "TRG_ADMIN_DBA_LOG" ENABLE;
