--------------------------------------------------------
--  DDL for Trigger TRG_DM_TREATM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_DM_TREATM" 
BEFORE INSERT OR UPDATE ON AMNIS.TREATM FOR EACH ROW
BEGIN
IF INSERTING THEN
IF 
 :NEW.TREATM_ID IS NULL THEN
  SELECT SEQ_BASE.NEXTVAL 
 INTO :NEW.TREATM_ID FROM DUAL;
END IF;
:NEW.CRD:=SYSTIMESTAMP;		   --LÉTREHOZÁS IDŐPONTJA
:NEW.CRU:=NVL(V('APP_USER'),USER);       --APEX USER AKI LÉTREHOZZA A REKORDOT
ELSIF UPDATING THEN 
  :NEW.MDD:=SYSTIMESTAMP;	     --MÓDOSÍTÁS IDŐPONTJA
  :NEW.MDU:=NVL(V('APP_USER'),USER);       --APEX USER AKI MÓDOSÍT
END IF;
END;
/
ALTER TRIGGER "TRG_DM_TREATM" ENABLE;
