--------------------------------------------------------
--  DDL for Index UQ_DMCU
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_DMCU" ON "DM_CAT_USAGE" ("CAT_TYPE_ID", "TABLE_NAME", "TABLE_COLUMN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
