--------------------------------------------------------
--  Constraints for Table VALID_UNIT
--------------------------------------------------------

  ALTER TABLE "VALID_UNIT" ADD CONSTRAINT "PK_VALU" UNIQUE ("VALID_UNIT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "VALID_UNIT" MODIFY ("VALID_UNIT_ID" NOT NULL DISABLE);
 
  ALTER TABLE "VALID_UNIT" MODIFY ("UNIT_ID" NOT NULL DISABLE);
 
  ALTER TABLE "VALID_UNIT" MODIFY ("UNIT_NAME" NOT NULL DISABLE);
 
  ALTER TABLE "VALID_UNIT" MODIFY ("UNIT" NOT NULL DISABLE);
 
  ALTER TABLE "VALID_UNIT" MODIFY ("ANALYSIS_TYPE_ID" NOT NULL DISABLE);
 
  ALTER TABLE "VALID_UNIT" MODIFY ("VALID_TYPE_ID" NOT NULL DISABLE);
