--------------------------------------------------------
--  DDL for Table WK_DM_SUPER_TYP
--------------------------------------------------------

  CREATE TABLE "WK_DM_SUPER_TYP" 
   (	"SUPER_TYP_ID" NUMBER(*,0), 
	"GROUP_ID" NUMBER(*,0), 
	"GROUND_LEVEL_ID" NUMBER(*,0), 
	"SUPER_TYPE_NAME" VARCHAR2(150 BYTE), 
	"SUPER_TYPE_SHORT_NAME" VARCHAR2(50 BYTE), 
	"SUPER_GROUP_NAME" VARCHAR2(100 BYTE), 
	"SLEVEL" NUMBER(*,0), 
	"SOPTIONAL" VARCHAR2(50 BYTE), 
	"WK_CLASS_ID" VARCHAR2(255 BYTE), 
	"FROM_DATE" DATE, 
	"TO_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(150 BYTE), 
	"USE_COMMENT" VARCHAR2(50 BYTE), 
	"CRU" VARCHAR2(50 BYTE), 
	"CRD" VARCHAR2(50 BYTE), 
	"MDU" VARCHAR2(50 BYTE), 
	"MDD" VARCHAR2(50 BYTE), 
	"DATA_OWNER_ID" NUMBER(*,0), 
	"STATUS_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
