//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TEXT
    {
        public long DM_TEXT_ID { get; set; }
        public Nullable<long> TEXT_ID { get; set; }
        public Nullable<long> LANGUAGE_ID { get; set; }
        public string TRANSL_TYPE { get; set; }
        public string CNAMES { get; set; }
        public string HELP_TEXT { get; set; }
        public string DESCRIPTION { get; set; }
        public string PRINT_TEXT { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string CRU { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public string MDU { get; set; }
        public Nullable<System.DateTime> MDD { get; set; }
        public string HUN_NAMES { get; set; }
        public string W_FORM { get; set; }
        public string W_LANGUAGE_CODE { get; set; }
        public string REFERENCE_CODE { get; set; }
        public string W_ERROR { get; set; }
        public string W_GROUP_NAME { get; set; }
        public long STATUS_ID { get; set; }
    }
}
