//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TRANSLATE
    {
        public Nullable<long> TRANSLATE_ID { get; set; }
        public Nullable<long> TEXT_ID { get; set; }
        public Nullable<long> DISPLAY_TYPE_ID { get; set; }
        public string TBL_NAME { get; set; }
        public string TBL_COL_NAME { get; set; }
        public Nullable<long> TBL_PK_ID { get; set; }
        public Nullable<long> TBL_ROWS { get; set; }
        public string APEX_VARIABLE { get; set; }
        public string PARAM_TYPE1 { get; set; }
        public string PARAM_VALUE1 { get; set; }
        public string PARAM_TYPE2 { get; set; }
        public string PARAM_VALUE2 { get; set; }
        public string DESCRIPTION { get; set; }
        public string W_GROUP_NAME { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string CRU { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public string MDU { get; set; }
        public Nullable<System.DateTime> MDD { get; set; }
        public string W_REFERENCE_CODE { get; set; }
        public string W_DISPLAY_TYPE { get; set; }
        public string W_APEX_VARIABLE { get; set; }
        public long STATUS_ID { get; set; }
        public Nullable<int> APEX_PAGE { get; set; }
    }
}
