//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsToDoDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_SUPER_TYP
    {
        public long SUPER_TYP_ID { get; set; }
        public Nullable<long> GROUP_ID { get; set; }
        public long GROUND_LEVEL_ID { get; set; }
        public string SUPER_TYPE_NAME { get; set; }
        public string SUPER_TYPE_SHORT_NAME { get; set; }
        public string SUPER_GROUP_NAME { get; set; }
        public Nullable<short> SLEVEL { get; set; }
        public Nullable<long> WK_CLASS_ID { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public System.DateTime TO_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string USE_COMMENT { get; set; }
        public string CRU { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public string MDU { get; set; }
        public Nullable<System.DateTime> MDD { get; set; }
        public Nullable<short> ROLL_TYPE { get; set; }
        public string WIRED_TO { get; set; }
    }
}
