//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsToDoDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_USER
    {
        public string USER_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string CRU { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public string MDU { get; set; }
        public Nullable<System.DateTime> MDD { get; set; }
        public long STATUS_ID { get; set; }
        public string USER_PSWD { get; set; }
        public long USER_ID { get; set; }
        public Nullable<long> SUBJ_ID { get; set; }
        public Nullable<long> LANGUAGE_ID { get; set; }
    }
}
