//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EsToDoDal
{
    using System;
    using System.Collections.Generic;
    
    public partial class WK_PF_MENU
    {
        public Nullable<decimal> LVL { get; set; }
        public string LABEL { get; set; }
        public string PAGE_ID { get; set; }
        public string IS_CURRENT_LIST_ENTRY { get; set; }
        public string IMAGE { get; set; }
        public string IMAGE_ATTRIBUTE { get; set; }
        public string IMAGE_ALT_ATTRIBUTE { get; set; }
        public Nullable<decimal> ORDER1 { get; set; }
        public Nullable<decimal> MENU_ID { get; set; }
        public Nullable<decimal> ORDER2 { get; set; }
        public Nullable<decimal> TREATM_GROUP_ID { get; set; }
        public string APEX_VARIABLE { get; set; }
        public short ROLL_TYPE { get; set; }
    }
}
