//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoModell
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERT_PARAM
    {
        public long ALERT_PARAM_ID { get; set; }
        public long ALERT_ID { get; set; }
        public long PARAM_TYPE_ID { get; set; }
        public Nullable<decimal> APEX_PAGE { get; set; }
        public string APEX_VARIABLE { get; set; }
        public string VALUE { get; set; }
        public string DESCRIPTION { get; set; }
        public long STATUS_ID { get; set; }
        public string CRU { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public string MDU { get; set; }
        public Nullable<System.DateTime> MDD { get; set; }
        public Nullable<long> SUBJ_ID { get; set; }
        public Nullable<decimal> APEX_PAGE_OLD { get; set; }
    
        public virtual ALERT ALERT { get; set; }
    }
}
