using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ToDoModell
{
    class Column
    {

    }
}


OWNER	TABLE_NAME	COLUMN_NAME	DATA_TYPE	DATA_TYPE_MOD	DATA_TYPE_OWNER	DATA_LENGTH	DATA_PRECISION	DATA_SCALE	NULLABLE	COLUMN_ID	DEFAULT_LENGTH	DATA_DEFAULT	NUM_DISTINCT	LOW_VALUE	HIGH_VALUE	DENSITY	NUM_NULLS	NUM_BUCKETS	LAST_ANALYZED	SAMPLE_SIZE	CHARACTER_SET_NAME	CHAR_COL_DECL_LENGTH	GLOBAL_STATS	USER_STATS	AVG_COL_LEN	CHAR_LENGTH	CHAR_USED	V80_FMT_IMAGE	DATA_UPGRADED	HIDDEN_COLUMN	VIRTUAL_COLUMN	SEGMENT_COLUMN_ID	INTERNAL_COLUMN_ID	HISTOGRAM	QUALIFIED_COL_NAME
OBH_TEST	DM_REGULATION	TCRITERION	VARCHAR2	(null)	(null)	4000	(null)	(null)	Y	41	(null)	(null)	0	(null)	(null)	0	1	0	2015.05.03. 6:00:54	(null)	CHAR_CS	4000	YES	NO	0	4000	B	NO	YES	NO	NO	41	41	NONE	TCRITERION