//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoModell
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_LANGUAGE
    {
        public long LANGUAGE_ID { get; set; }
        public string LANGUAGE_NAME { get; set; }
        public string LANGUAGE_TYP { get; set; }
        public string RL { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string CRU { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public string MDU { get; set; }
        public Nullable<System.DateTime> MDD { get; set; }
        public string LANGUAGE_CODE { get; set; }
        public string W_COUNTRY_TRICODE { get; set; }
        public string ISO639_3 { get; set; }
        public string ISO639_2 { get; set; }
        public string ISO639_1 { get; set; }
        public string HUN_NAME { get; set; }
        public string ENG_NAME { get; set; }
        public long STATUS_ID { get; set; }
        public Nullable<long> FLAG_ID { get; set; }
    }
}
