//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoModell
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_TREATM
    {
        public long DM_TREATM_ID { get; set; }
        public Nullable<long> TREATM_TYPE_ID { get; set; }
        public Nullable<long> TREATM_CATEGORY_ID { get; set; }
        public Nullable<long> TREATM_GROUP_ID { get; set; }
        public Nullable<long> TREATM_PARAM_TYPE_ID { get; set; }
        public Nullable<short> MANDATORY { get; set; }
        public Nullable<short> MULTIPLY { get; set; }
        public string TABLE_ROLL { get; set; }
        public Nullable<short> ROLL_TYPE { get; set; }
        public Nullable<short> ORDER_NO { get; set; }
        public Nullable<long> VALUE_GROUP_ID { get; set; }
        public string VALUE_GROUP_TABLE { get; set; }
        public Nullable<short> VALUE_ALLOWED { get; set; }
        public Nullable<long> DIMENSION_GROUP_ID { get; set; }
        public Nullable<short> DIMENSION_ALLOWED { get; set; }
        public Nullable<long> USER_TYPE1_GROUP { get; set; }
        public Nullable<long> USER_TYPE2_GROUP { get; set; }
        public Nullable<long> SUBJ_GROUP_ID { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public string CRU { get; set; }
        public Nullable<System.DateTime> MDD { get; set; }
        public string MDU { get; set; }
        public Nullable<short> PARAM_VISIBLE { get; set; }
        public string VALUE_TYPE { get; set; }
    
        public virtual DM_SUPER_TYP DM_SUPER_TYP { get; set; }
        public virtual DM_SUPER_TYP DM_SUPER_TYP1 { get; set; }
    }
}
