//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoModell
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EsToDoEntities : DbContext
    {
        public EsToDoEntities()
            : base("name=EsToDoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DM_LANGUAGE> DM_LANGUAGE { get; set; }
        public DbSet<DM_SUPER_TYP> DM_SUPER_TYP { get; set; }
        public DbSet<DM_TEXT> DM_TEXT { get; set; }
        public DbSet<DM_TRANSLATE> DM_TRANSLATE { get; set; }
        public DbSet<DM_TREATM> DM_TREATM { get; set; }
        public DbSet<TREATM> TREATMs { get; set; }
        public DbSet<TREATM_PARAM> TREATM_PARAM { get; set; }
        public DbSet<TREATM_REL> TREATM_REL { get; set; }
        public DbSet<VT_DM_TRANSLATE> VT_DM_TRANSLATE { get; set; }
    }
}
