//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoModell
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREATM_REL
    {
        public long TREATM_REL_ID { get; set; }
        public long TREATM_ID1 { get; set; }
        public long TREATM_ID2 { get; set; }
        public string KOD1 { get; set; }
        public string KOD2 { get; set; }
        public long REL_TYPE_ID { get; set; }
        public string EXTRA_NEXT_STEP { get; set; }
        public Nullable<long> EPI_ID { get; set; }
        public Nullable<short> ORDER_NO { get; set; }
        public Nullable<System.DateTime> TIME_START { get; set; }
        public Nullable<System.DateTime> TIME_END { get; set; }
        public Nullable<long> MM_ID { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<long> STATUS_ID { get; set; }
        public string CRU { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public string MDU { get; set; }
        public Nullable<System.DateTime> MDD { get; set; }
        public Nullable<short> GO_ORDER_NO { get; set; }
    }
}
