//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoModell
{
    using System;
    using System.Collections.Generic;
    
    public partial class TREATM_PARAM
    {
        public TREATM_PARAM()
        {
            this.TREATM_PARAM1 = new HashSet<TREATM_PARAM>();
        }
    
        public long TREATM_PARAM_ID { get; set; }
        public Nullable<long> TREATM_PARAM1_ID { get; set; }
        public long TREATM_ID { get; set; }
        public long EPI_ID { get; set; }
        public Nullable<long> SUBJ_ID { get; set; }
        public Nullable<long> SUBJ_TYPE_ID { get; set; }
        public long PARAM_TYPE_ID { get; set; }
        public string VALUE { get; set; }
        public Nullable<long> UNIT_TYPE_ID { get; set; }
        public Nullable<long> VALUE_TYPE_ID { get; set; }
        public Nullable<short> ORDER_NO { get; set; }
        public Nullable<long> MM_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string CRU { get; set; }
        public Nullable<System.DateTime> CRD { get; set; }
        public string MDU { get; set; }
        public Nullable<System.DateTime> MDD { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public System.DateTime TO_DATE { get; set; }
        public string UNIT { get; set; }
        public Nullable<long> FIELD_TYPE_ID { get; set; }
        public Nullable<short> ROLL_TYPE { get; set; }
    
        public virtual TREATM TREATM { get; set; }
        public virtual ICollection<TREATM_PARAM> TREATM_PARAM1 { get; set; }
        public virtual TREATM_PARAM TREATM_PARAM2 { get; set; }
    }
}
