//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoModell
{
    using System;
    using System.Collections.Generic;
    
    public partial class VT_DM_TRANSLATE
    {
        public long DM_TEXT_ID { get; set; }
        public Nullable<long> TEXT_ID { get; set; }
        public Nullable<long> LANGUAGE_ID { get; set; }
        public string TRANSL_TYPE { get; set; }
        public string NAMES { get; set; }
        public string HELP_TEXT { get; set; }
        public string TEXT_DESCRIPTION { get; set; }
        public string PRINT_TEXT { get; set; }
        public Nullable<System.DateTime> TEXT_FROM_DAT { get; set; }
        public Nullable<System.DateTime> TEXT_TO_DATE { get; set; }
        public string HUN_NAMES { get; set; }
        public string REFERENCE_CODE { get; set; }
        public long TRANSLATE_ID { get; set; }
        public Nullable<long> DISPLAY_TYPE_ID { get; set; }
        public string TBL_NAME { get; set; }
        public string TBL_COL_NAME { get; set; }
        public Nullable<long> TBL_PK_ID { get; set; }
        public Nullable<long> TBL_ROWS { get; set; }
        public string APEX_VARIABLE { get; set; }
        public Nullable<int> APEX_VARIABLE_PAGE { get; set; }
        public string PARAM_TYPE1 { get; set; }
        public string PARAM_VALUE1 { get; set; }
        public string PARAM_TYPE2 { get; set; }
        public string PARAM_VALUE2 { get; set; }
        public string TRANSLATE_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> TRANSLATE_FROM_DATE { get; set; }
        public Nullable<System.DateTime> TRANSLATE_TO_DATE { get; set; }
    }
}
