DROP TYPE OBH_TEST.VALUE_LIST;

CREATE OR REPLACE TYPE OBH_TEST.VALUE_LIST_ITEM AS OBJECT (
   DISPLAY VARCHAR2(255),
   VALUE NUMBER (12,0)
);
/
CREATE TYPE OBH_TEST.VALUE_LIST AS
    TABLE OF OBH_TEST.VALUE_LIST_ITEM;
/