--
-- Script was generated by Devart dbForge Studio for Oracle, Version 3.7.472.0
-- Product home page: http://www.devart.com/dbforge/oracle/studio
-- Script date 2015.06.05. 12:58:47
-- Server version: Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
-- Client version: 12.1.0.0
-- Please backup your database before running this script
--

--
-- Create table "OBH_TEST."tmp_devart_DM_XL_REL""
--
CREATE TABLE OBH_TEST."tmp_devart_DM_XL_REL" (
  DM_XL_REL_ID NUMBER(12, 0),
  DM_XL_ID1 NUMBER(12, 0),
  DM_XL_ID2 NUMBER(12, 0),
  DM_XL_ID3 NUMBER(12, 0),
  REL_TYPE_ID NUMBER(12, 0),
  MATHOP VARCHAR2(50 BYTE),
  CONNUM NUMBER(12, 2) DEFAULT 1,
  ORDER_NO NUMBER(2, 0),
  W_REL_TYPE_NAME VARCHAR2(50 BYTE),
  W_ORDER_NO1 NUMBER(4, 0),
  W_ORDER_NO2 NUMBER(4, 0),
  W_ORDER_REG VARCHAR2(50 BYTE),
  W_ORDER_NO3 NUMBER(4, 0),
  FROM_DATE DATE,
  TO_DATE DATE,
  DESCRIPTION VARCHAR2(255 BYTE),
  CRU VARCHAR2(30 BYTE),
  CRD TIMESTAMP(6) DEFAULT SYSDATE,
  MDU VARCHAR2(30 BYTE),
  MDD TIMESTAMP(6))
TABLESPACE USERS
STORAGE (
  INITIAL 64K
  NEXT 1M
  MAXEXTENTS UNLIMITED
)
LOGGING;

COMMENT ON TABLE OBH_TEST."tmp_devart_DM_XL_REL" IS 'A betöltési szabályok relációs, műveleti szabályok relációja';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".CONNUM IS 'A szorzó szám értéke (alapértelmezetten 1)';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".CRD IS 'Rekord Létrehozásának időpecsétje';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".CRU IS 'Rekord Létrehozójának Azonosítója';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".DESCRIPTION IS 'Leírás';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".DM_XL_ID1 IS 'Első operandus';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".DM_XL_ID2 IS 'Második operndus';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".DM_XL_ID3 IS 'Az eredmény azonosítója';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".DM_XL_REL_ID IS 'A tábla egyedi azonosítója';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".FROM_DATE IS 'Érvényesség kezdő időpontja';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".MATHOP IS 'Matematikai operátor';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".MDD IS 'Rekord Módosításának Időpecsétje';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".MDU IS 'Rekord Módosítójának Azonosítója';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".ORDER_NO IS 'Sorrend';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".REL_TYPE_ID IS 'Reláció típusa';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".TO_DATE IS 'Érvényesség vége';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".W_ORDER_NO1 IS 'Az ID1 sorrendjének sorszáma';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".W_ORDER_NO2 IS 'Az ID2 sorrendjének sorszáma';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".W_ORDER_NO3 IS 'Az ID3 sorrendjének sorszáma';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".W_ORDER_REG IS 'Az összegzés (számolás) menete';
COMMENT ON COLUMN OBH_TEST."tmp_devart_DM_XL_REL".W_REL_TYPE_NAME IS 'A reláció megnevezése szövegesen';

--
-- Restore data to the table "OBH_TEST."tmp_devart_DM_XL_REL""
--
INSERT INTO OBH_TEST."tmp_devart_DM_XL_REL"(DM_XL_REL_ID, DM_XL_ID1, DM_XL_ID2, DM_XL_ID3, REL_TYPE_ID, W_REL_TYPE_NAME, MATHOP, CONNUM, W_ORDER_NO1, W_ORDER_NO2, W_ORDER_REG, W_ORDER_NO3, FROM_DATE, TO_DATE, DESCRIPTION, CRU, CRD, MDU, MDD)
  SELECT DM_XL_REL_ID, DM_XL_ID1, DM_XL_ID2, DM_XL_ID3, REL_TYPE_ID, W_REL_TYPE_NAME, MATHOP, CONNUM, W_ORDER_NO1, W_ORDER_NO2, W_ORDER_REG, W_ORDER_NO3, FROM_DATE, TO_DATE, DESCRIPTION, CRU, CRD, MDU, MDD FROM OBH_TEST.DM_XL_REL;

--
-- Drop table "OBH_TEST.DM_XL_REL"
--
DROP TABLE OBH_TEST.DM_XL_REL CASCADE CONSTRAINTS;

--
-- Rename table "OBH_TEST."tmp_devart_DM_XL_REL"" to "DM_XL_REL"
--
ALTER TABLE OBH_TEST."tmp_devart_DM_XL_REL" RENAME TO DM_XL_REL;

--
-- Create unique key "PK_DM_XL_REL" on table "OBH_TEST.DM_XL_REL"
--
ALTER TABLE OBH_TEST.DM_XL_REL
  ADD CONSTRAINT PK_DM_XL_REL PRIMARY KEY (DM_XL_REL_ID) DISABLE;

--
-- Create check constraint on table "OBH_TEST.DM_XL_REL"
--
ALTER TABLE OBH_TEST.DM_XL_REL
  ADD CHECK ("DM_XL_ID1" IS NOT NULL) DISABLE;

--
-- Create check constraint on table "OBH_TEST.DM_XL_REL"
--
ALTER TABLE OBH_TEST.DM_XL_REL
  ADD CHECK ("DM_XL_ID2" IS NOT NULL) DISABLE;