--
-- Script was generated by Devart dbForge Studio for Oracle, Version 3.7.472.0
-- Product home page: http://www.devart.com/dbforge/oracle/studio
-- Script date 2015.03.30. 11:40:59
-- Server version: Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production With the Partitioning, Oracle Label Security, OLAP, Data Mining, Oracle Database Vault and Real Application Testing options
-- Client version: 12.1.0.0
-- Please backup your database before running this script
--

--
-- Alter column "ORDER_NO" on table "OBH_TEST.DM_SUBJECT"
--
ALTER TABLE OBH_TEST.DM_SUBJECT
  MODIFY(ORDER_NO NUMBER(4, 0) DEFAULT NULL);

--
-- Create column "DIMENSION_ALLOWED" on table "OBH_TEST.DM_SUBJECT"
--
ALTER TABLE OBH_TEST.DM_SUBJECT
  ADD DIMENSION_ALLOWED NUMBER(1, 0);

--
-- Create column "TABLE_ROLL" on table "OBH_TEST.DM_SUBJECT"
--
ALTER TABLE OBH_TEST.DM_SUBJECT
  ADD TABLE_ROLL NVARCHAR2(50) DEFAULT 'SUBJ_PARAM';