--
-- Script was generated by Devart dbForge Studio for Oracle, Version 3.7.472.0
-- Product home page: http://www.devart.com/dbforge/oracle/studio
-- Script date 2015.03.31. 8:04:12
-- Server version: Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production With the Partitioning, Oracle Label Security, OLAP, Data Mining, Oracle Database Vault and Real Application Testing options
-- Client version: 12.1.0.0
-- Please backup your database before running this script
--

--
-- Alter function "OBH_TEST.SEARCH_GROUND_LEVEL_ID"
--
CREATE OR REPLACE FUNCTION OBH_TEST.SEARCH_FIRST_LEVEL_ID (p_super_type_id NUMBER)
  RETURN NUMBER
AS
  v_super_typ_row dm_super_typ%rowtype;
BEGIN
  if p_super_type_id is null then
     return null;
  end if;

  select * INTO v_super_typ_row FROM DM_SUPER_TYP WHERE SUPER_TYP_ID = p_super_type_id;
  
  if v_super_typ_row.SLEVEL = 1 then
     return v_super_typ_row.super_typ_id;
  elsif v_super_typ_row.SLEVEL > 0 then
     return SEARCH_FIRST_LEVEL_ID (v_super_typ_row.group_id);
  else 
     return null;
  end if; 

END;

--
-- Script was generated by Devart dbForge Studio for Oracle, Version 3.7.472.0
-- Product home page: http://www.devart.com/dbforge/oracle/studio
-- Script date 2015.03.31. 9:30:40
-- Server version: Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production With the Partitioning, Oracle Label Security, OLAP, Data Mining, Oracle Database Vault and Real Application Testing options
-- Client version: 12.1.0.0
-- Please backup your database before running this script
--

--
-- Create column "SUBJ_CATEGORY_ID" on table "OBH_TEST.SUBJECT"
--
ALTER TABLE OBH_TEST.SUBJECT
  ADD SUBJ_CATEGORY_ID NUMBER(12, 0);