--
-- Script was generated by Devart dbForge Studio for Oracle, Version 3.7.472.0
-- Product home page: http://www.devart.com/dbforge/oracle/studio
-- Script date 2015.04.01. 9:03:16
-- Server version: Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production With the Partitioning, Oracle Label Security, OLAP, Data Mining, Oracle Database Vault and Real Application Testing options
-- Client version: 12.1.0.0
-- Please backup your database before running this script
--

--
-- Alter function "OBH_TEST.LOOKUP_SUBJ_NAME"
--
CREATE OR REPLACE FUNCTION OBH_TEST."LOOKUP_SUBJ_NAME" 
(
  P_SUBJ_ID number
) return varchar2 as 

 v_ret varchar2 (2000);
begin
  begin
    v_ret := GET_SUBJECT_NAME(P_SUBJ_ID);
  EXCEPTION 
  when OTHERS then
    return null;
 end;
 return V_RET;
END LOOKUP_SUBJ_NAME;
