--
-- Script was generated by Devart dbForge Studio for Oracle, Version 3.7.472.0
-- Product home page: http://www.devart.com/dbforge/oracle/studio
-- Script date 2015.03.24. 12:52:58
-- Server version: Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production With the Partitioning, Oracle Label Security, OLAP, Data Mining, Oracle Database Vault and Real Application Testing options
-- Client version: 12.1.0.0
-- Please backup your database before running this script
--

--
-- Drop column "DATA_OWNER_ID" from table "DM_SUPER_TYP"
--
ALTER TABLE DM_SUPER_TYP
  DROP COLUMN DATA_OWNER_ID;

--
-- Drop column "SUBJ_NAME" from table "SUBJECT"
--
ALTER TABLE SUBJECT
  DROP COLUMN SUBJ_NAME;

--
-- Drop column "SUBJ_SHORT_NAME" from table "SUBJECT"
--
ALTER TABLE SUBJECT
  DROP COLUMN SUBJ_SHORT_NAME;

--
-- Drop column "TYPE_ID" from table "SUBJECT"
--
ALTER TABLE SUBJECT
  DROP COLUMN TYPE_ID;

--
-- Drop column "WK_TYPE_NAME" from table "SUBJECT"
--
ALTER TABLE SUBJECT
  DROP COLUMN WK_TYPE_NAME;

--
-- Drop column "USER_TYPE_ID" from table "SUBJECT"
--
ALTER TABLE SUBJECT
  DROP COLUMN USER_TYPE_ID;

--
-- Drop column "OFFICE_ID" from table "SUBJECT"
--
ALTER TABLE SUBJECT
  DROP COLUMN OFFICE_ID;

--
-- Create column "SUBJ_TYPE_ID" on table "SUBJ_PARAM"
--
ALTER TABLE SUBJ_PARAM
  ADD SUBJ_TYPE_ID NUMBER(10);


