--
-- Script was generated by Devart dbForge Studio for Oracle, Version 3.7.472.0
-- Product home page: http://www.devart.com/dbforge/oracle/studio
-- Script date 2015.03.23. 18:05:21
-- Server version: Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production With the Partitioning, Oracle Label Security, OLAP, Data Mining, Oracle Database Vault and Real Application Testing options
-- Client version: 12.1.0.0
-- Please backup your database before running this script
--

--
-- Alter column "FROM_DATE" on table "OBH_TEST.SUBJECT"
--
ALTER TABLE SUBJECT
  MODIFY(FROM_DATE DEFAULT SYSDATE);

--
-- Alter column "TO_DATE" on table "OBH_TEST.SUBJECT"
--
ALTER TABLE SUBJECT
  MODIFY(TO_DATE DEFAULT TO_DATE('2099.12.31. 23:59:59','YYYY.MM.DD. HH24:MI:SS'));

--
-- Create column "ROLL_TYPE" on table "OBH_TEST.SUBJECT"
--
ALTER TABLE SUBJECT
  ADD ROLL_TYPE NUMBER(*, 0) DEFAULT 1;

--
-- Create column "ROLL_TYPE" on table "OBH_TEST.DM_SUPER_TYP"
--
ALTER TABLE DM_SUPER_TYP
  ADD ROLL_TYPE NUMBER(*, 0) DEFAULT 1;

--
-- Alter column "FROM_DATE" on table "OBH_TEST.DM_SUPER_TYP"
--
ALTER TABLE DM_SUPER_TYP
  MODIFY(FROM_DATE DEFAULT SYSDATE);

--
-- Alter column "TO_DATE" on table "OBH_TEST.DM_SUPER_TYP"
--
ALTER TABLE DM_SUPER_TYP
  MODIFY(TO_DATE DEFAULT TO_DATE('2099.12.31. 23:59:59','YYYY.MM.DD. HH24:MI:SS'));

--
-- Create column "WIRED_TO" on table "OBH_TEST.DM_SUPER_TYP"
--
ALTER TABLE OBH_TEST.DM_SUPER_TYP
  ADD WIRED_TO NVARCHAR2(255);